In [1]:
import glob
import functools
import datetime as dt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
import re
import numpy as np 
import pandas as pd

# Input data files are available in the read-only "../input/" directory

import os

In [44]:
import glob
import csv

read_files = glob.glob('D:\Object_casedocs\*')

with open("casedocs.csv", "w") as outfile:
    w=csv.writer(outfile)
    for f in read_files:
        with open(f, "r") as infile:
            w.writerow([" ".join([line.strip() for line in infile])])

lst_arr = os.listdir("D:\Object_casedocs")
df_filename = pd.DataFrame(lst_arr, columns = ['Name'])
df_filename

           Name
0        C1.txt
1       C10.txt
2      C100.txt
3     C1000.txt
4     C1001.txt
...         ...
2909   C995.txt
2910   C996.txt
2911   C997.txt
2912   C998.txt
2913   C999.txt

[2914 rows x 1 columns]

In [45]:
for dirname, _, filenames in os.walk("D:\Object_casedocs"):
    for filename in filenames:
        print(os.path.join(dirname, filename))

D:\Object_casedocs\C1.txt
D:\Object_casedocs\C10.txt
D:\Object_casedocs\C100.txt
D:\Object_casedocs\C1000.txt
D:\Object_casedocs\C1001.txt
D:\Object_casedocs\C1002.txt
D:\Object_casedocs\C1003.txt
D:\Object_casedocs\C1004.txt
D:\Object_casedocs\C1005.txt
D:\Object_casedocs\C1006.txt
D:\Object_casedocs\C1007.txt
D:\Object_casedocs\C1008.txt
D:\Object_casedocs\C1009.txt
D:\Object_casedocs\C101.txt
D:\Object_casedocs\C1010.txt
D:\Object_casedocs\C1011.txt
D:\Object_casedocs\C1012.txt
D:\Object_casedocs\C1013.txt
D:\Object_casedocs\C1014.txt
D:\Object_casedocs\C1015.txt
D:\Object_casedocs\C1016.txt
D:\Object_casedocs\C1017.txt
D:\Object_casedocs\C1018.txt
D:\Object_casedocs\C1019.txt
D:\Object_casedocs\C102.txt
D:\Object_casedocs\C1020.txt
D:\Object_casedocs\C1021.txt
D:\Object_casedocs\C1022.txt
D:\Object_casedocs\C1023.txt
D:\Object_casedocs\C1024.txt
D:\Object_casedocs\C1025.txt
D:\Object_casedocs\C1026.txt
D:\Object_casedocs\C1027.txt
D:\Object_casedocs\C1028.txt
D:\Object_casedocs\C1029.txt
D:\Object_casedocs\C103.txt
D:\Object_casedocs\C1030.txt
D:\Object_casedocs\C1031.txt
D:\Object_casedocs\C1032.txt
D:\Object_casedocs\C1033.txt
D:\Object_casedocs\C1034.txt
D:\Object_casedocs\C1035.txt
D:\Object_casedocs\C1036.txt
D:\Object_casedocs\C1037.txt
D:\Object_casedocs\C1038.txt
D:\Object_casedocs\C1039.txt
D:\Object_casedocs\C104.txt
D:\Object_casedocs\C1040.txt
D:\Object_casedocs\C1041.txt
D:\Object_casedocs\C1042.txt
D:\Object_casedocs\C1043.txt
D:\Object_casedocs\C1044.txt
D:\Object_casedocs\C1045.txt
D:\Object_casedocs\C1046.txt
D:\Object_casedocs\C1047.txt
D:\Object_casedocs\C1048.txt
D:\Object_casedocs\C1049.txt
D:\Object_casedocs\C105.txt
D:\Object_casedocs\C1050.txt
D:\Object_casedocs\C1051.txt
D:\Object_casedocs\C1052.txt
D:\Object_casedocs\C1053.txt
D:\Object_casedocs\C1054.txt
D:\Object_casedocs\C1055.txt
D:\Object_casedocs\C1056.txt
D:\Object_casedocs\C1057.txt
D:\Object_casedocs\C1058.txt
D:\Object_casedocs\C1059.txt
D:\Object_casedocs\C106.txt
D:\Object_casedocs\C1060.txt
D:\Object_casedocs\C1061.txt
D:\Object_casedocs\C1062.txt
D:\Object_casedocs\C1063.txt
D:\Object_casedocs\C1064.txt
D:\Object_casedocs\C1065.txt
D:\Object_casedocs\C1066.txt
D:\Object_casedocs\C1067.txt
D:\Object_casedocs\C1068.txt
D:\Object_casedocs\C1069.txt
D:\Object_casedocs\C107.txt
D:\Object_casedocs\C1070.txt
D:\Object_casedocs\C1071.txt
D:\Object_casedocs\C1072.txt
D:\Object_casedocs\C1073.txt
D:\Object_casedocs\C1074.txt
D:\Object_casedocs\C1075.txt
D:\Object_casedocs\C1076.txt
D:\Object_casedocs\C1077.txt
D:\Object_casedocs\C1078.txt
D:\Object_casedocs\C1079.txt
D:\Object_casedocs\C108.txt
D:\Object_casedocs\C1080.txt
D:\Object_casedocs\C1081.txt
D:\Object_casedocs\C1082.txt
D:\Object_casedocs\C1083.txt
D:\Object_casedocs\C1084.txt
D:\Object_casedocs\C1085.txt
D:\Object_casedocs\C1086.txt
D:\Object_casedocs\C1087.txt
D:\Object_casedocs\C1088.txt
D:\Object_casedocs\C1089.txt
D:\Object_casedocs\C109.txt
D:\Object_casedocs\C1090.txt
D:\Object_casedocs\C1091.txt
D:\Object_casedocs\C1092.txt
D:\Object_casedocs\C1093.txt
D:\Object_casedocs\C1094.txt
D:\Object_casedocs\C1095.txt
D:\Object_casedocs\C1096.txt
D:\Object_casedocs\C1097.txt
D:\Object_casedocs\C1098.txt
D:\Object_casedocs\C1099.txt
D:\Object_casedocs\C11.txt
D:\Object_casedocs\C110.txt
D:\Object_casedocs\C1100.txt
D:\Object_casedocs\C1101.txt
D:\Object_casedocs\C1102.txt
D:\Object_casedocs\C1103.txt
D:\Object_casedocs\C1104.txt
D:\Object_casedocs\C1105.txt
D:\Object_casedocs\C1106.txt
D:\Object_casedocs\C1107.txt
D:\Object_casedocs\C1108.txt
D:\Object_casedocs\C1109.txt
D:\Object_casedocs\C111.txt
D:\Object_casedocs\C1110.txt
D:\Object_casedocs\C1111.txt
D:\Object_casedocs\C1112.txt
D:\Object_casedocs\C1113.txt
D:\Object_casedocs\C1114.txt
D:\Object_casedocs\C1115.txt
D:\Object_casedocs\C1116.txt
D:\Object_casedocs\C1117.txt
D:\Object_casedocs\C1118.txt
D:\Object_casedocs\C1119.txt
D:\Object_casedocs\C112.txt
D:\Object_casedocs\C1120.txt
D:\Object_casedocs\C1121.txt
D:\Object_casedocs\C1122.txt
D:\Object_casedocs\C1123.txt
D:\Object_casedocs\C1124.txt
D:\Object_casedocs\C1125.txt
D:\Object_casedocs\C1126.txt
D:\Object_casedocs\C1127.txt
D:\Object_casedocs\C1128.txt
D:\Object_casedocs\C1129.txt
D:\Object_casedocs\C113.txt
D:\Object_casedocs\C1130.txt
D:\Object_casedocs\C1131.txt
D:\Object_casedocs\C1132.txt
D:\Object_casedocs\C1133.txt
D:\Object_casedocs\C1134.txt
D:\Object_casedocs\C1135.txt
D:\Object_casedocs\C1136.txt
D:\Object_casedocs\C1137.txt
D:\Object_casedocs\C1138.txt
D:\Object_casedocs\C1139.txt
D:\Object_casedocs\C114.txt
D:\Object_casedocs\C1140.txt
D:\Object_casedocs\C1141.txt
D:\Object_casedocs\C1142.txt
D:\Object_casedocs\C1143.txt
D:\Object_casedocs\C1144.txt
D:\Object_casedocs\C1145.txt
D:\Object_casedocs\C1146.txt
D:\Object_casedocs\C1147.txt
D:\Object_casedocs\C1148.txt
D:\Object_casedocs\C1149.txt
D:\Object_casedocs\C115.txt
D:\Object_casedocs\C1150.txt
D:\Object_casedocs\C1151.txt
D:\Object_casedocs\C1152.txt
D:\Object_casedocs\C1153.txt
D:\Object_casedocs\C1154.txt
D:\Object_casedocs\C1155.txt
D:\Object_casedocs\C1156.txt
D:\Object_casedocs\C1157.txt
D:\Object_casedocs\C1158.txt
D:\Object_casedocs\C1159.txt
D:\Object_casedocs\C116.txt
D:\Object_casedocs\C1160.txt
D:\Object_casedocs\C1161.txt
D:\Object_casedocs\C1162.txt
D:\Object_casedocs\C1163.txt
D:\Object_casedocs\C1164.txt
D:\Object_casedocs\C1165.txt
D:\Object_casedocs\C1166.txt
D:\Object_casedocs\C1167.txt
D:\Object_casedocs\C1168.txt
D:\Object_casedocs\C1169.txt
D:\Object_casedocs\C117.txt
D:\Object_casedocs\C1170.txt
D:\Object_casedocs\C1171.txt
D:\Object_casedocs\C1172.txt
D:\Object_casedocs\C1173.txt
D:\Object_casedocs\C1174.txt
D:\Object_casedocs\C1175.txt
D:\Object_casedocs\C1176.txt
D:\Object_casedocs\C1177.txt
D:\Object_casedocs\C1178.txt
D:\Object_casedocs\C1179.txt
D:\Object_casedocs\C118.txt
D:\Object_casedocs\C1180.txt
D:\Object_casedocs\C1181.txt
D:\Object_casedocs\C1182.txt
D:\Object_casedocs\C1183.txt
D:\Object_casedocs\C1184.txt
D:\Object_casedocs\C1185.txt
D:\Object_casedocs\C1186.txt
D:\Object_casedocs\C1187.txt
D:\Object_casedocs\C1188.txt
D:\Object_casedocs\C1189.txt
D:\Object_casedocs\C119.txt
D:\Object_casedocs\C1190.txt
D:\Object_casedocs\C1191.txt
D:\Object_casedocs\C1192.txt
D:\Object_casedocs\C1193.txt
D:\Object_casedocs\C1194.txt
D:\Object_casedocs\C1195.txt
D:\Object_casedocs\C1196.txt
D:\Object_casedocs\C1197.txt
D:\Object_casedocs\C1198.txt
D:\Object_casedocs\C1199.txt
D:\Object_casedocs\C12.txt
D:\Object_casedocs\C120.txt
D:\Object_casedocs\C1200.txt
D:\Object_casedocs\C1201.txt
D:\Object_casedocs\C1202.txt
D:\Object_casedocs\C1203.txt
D:\Object_casedocs\C1204.txt
D:\Object_casedocs\C1205.txt
D:\Object_casedocs\C1206.txt
D:\Object_casedocs\C1207.txt
D:\Object_casedocs\C1208.txt
D:\Object_casedocs\C1209.txt
D:\Object_casedocs\C121.txt
D:\Object_casedocs\C1210.txt
D:\Object_casedocs\C1211.txt
D:\Object_casedocs\C1212.txt
D:\Object_casedocs\C1213.txt
D:\Object_casedocs\C1214.txt
D:\Object_casedocs\C1215.txt
D:\Object_casedocs\C1216.txt
D:\Object_casedocs\C1217.txt
D:\Object_casedocs\C1218.txt
D:\Object_casedocs\C1219.txt
D:\Object_casedocs\C122.txt
D:\Object_casedocs\C1220.txt
D:\Object_casedocs\C1221.txt
D:\Object_casedocs\C1222.txt
D:\Object_casedocs\C1223.txt
D:\Object_casedocs\C1224.txt
D:\Object_casedocs\C1225.txt
D:\Object_casedocs\C1226.txt
D:\Object_casedocs\C1227.txt
D:\Object_casedocs\C1228.txt
D:\Object_casedocs\C1229.txt
D:\Object_casedocs\C123.txt
D:\Object_casedocs\C1230.txt
D:\Object_casedocs\C1231.txt
D:\Object_casedocs\C1232.txt
D:\Object_casedocs\C1233.txt
D:\Object_casedocs\C1234.txt
D:\Object_casedocs\C1235.txt
D:\Object_casedocs\C1236.txt
D:\Object_casedocs\C1237.txt
D:\Object_casedocs\C1238.txt
D:\Object_casedocs\C1239.txt
D:\Object_casedocs\C124.txt
D:\Object_casedocs\C1240.txt
D:\Object_casedocs\C1241.txt
D:\Object_casedocs\C1242.txt
D:\Object_casedocs\C1243.txt
D:\Object_casedocs\C1244.txt
D:\Object_casedocs\C1245.txt
D:\Object_casedocs\C1246.txt
D:\Object_casedocs\C1247.txt
D:\Object_casedocs\C1248.txt
D:\Object_casedocs\C1249.txt
D:\Object_casedocs\C125.txt
D:\Object_casedocs\C1250.txt
D:\Object_casedocs\C1251.txt
D:\Object_casedocs\C1252.txt
D:\Object_casedocs\C1253.txt
D:\Object_casedocs\C1254.txt
D:\Object_casedocs\C1255.txt
D:\Object_casedocs\C1256.txt
D:\Object_casedocs\C1257.txt
D:\Object_casedocs\C1258.txt
D:\Object_casedocs\C1259.txt
D:\Object_casedocs\C126.txt
D:\Object_casedocs\C1260.txt
D:\Object_casedocs\C1261.txt
D:\Object_casedocs\C1262.txt
D:\Object_casedocs\C1263.txt
D:\Object_casedocs\C1264.txt
D:\Object_casedocs\C1265.txt
D:\Object_casedocs\C1266.txt
D:\Object_casedocs\C1267.txt
D:\Object_casedocs\C1268.txt
D:\Object_casedocs\C1269.txt
D:\Object_casedocs\C127.txt
D:\Object_casedocs\C1270.txt
D:\Object_casedocs\C1271.txt
D:\Object_casedocs\C1272.txt
D:\Object_casedocs\C1273.txt
D:\Object_casedocs\C1274.txt
D:\Object_casedocs\C1275.txt
D:\Object_casedocs\C1276.txt
D:\Object_casedocs\C1277.txt
D:\Object_casedocs\C1278.txt
D:\Object_casedocs\C1279.txt
D:\Object_casedocs\C128.txt
D:\Object_casedocs\C1280.txt
D:\Object_casedocs\C1281.txt
D:\Object_casedocs\C1282.txt
D:\Object_casedocs\C1283.txt
D:\Object_casedocs\C1284.txt
D:\Object_casedocs\C1285.txt
D:\Object_casedocs\C1286.txt
D:\Object_casedocs\C1287.txt
D:\Object_casedocs\C1288.txt
D:\Object_casedocs\C1289.txt
D:\Object_casedocs\C129.txt
D:\Object_casedocs\C1290.txt
D:\Object_casedocs\C1291.txt
D:\Object_casedocs\C1292.txt
D:\Object_casedocs\C1293.txt
D:\Object_casedocs\C1294.txt
D:\Object_casedocs\C1295.txt
D:\Object_casedocs\C1296.txt
D:\Object_casedocs\C1297.txt
D:\Object_casedocs\C1298.txt
D:\Object_casedocs\C1299.txt
D:\Object_casedocs\C13.txt
D:\Object_casedocs\C130.txt
D:\Object_casedocs\C1300.txt
D:\Object_casedocs\C1301.txt
D:\Object_casedocs\C1302.txt
D:\Object_casedocs\C1303.txt
D:\Object_casedocs\C1304.txt
D:\Object_casedocs\C1305.txt
D:\Object_casedocs\C1306.txt
D:\Object_casedocs\C1307.txt
D:\Object_casedocs\C1308.txt
D:\Object_casedocs\C1309.txt
D:\Object_casedocs\C131.txt
D:\Object_casedocs\C1310.txt
D:\Object_casedocs\C1311.txt
D:\Object_casedocs\C1312.txt
D:\Object_casedocs\C1313.txt
D:\Object_casedocs\C1314.txt
D:\Object_casedocs\C1315.txt
D:\Object_casedocs\C1316.txt
D:\Object_casedocs\C1317.txt
D:\Object_casedocs\C1318.txt
D:\Object_casedocs\C1319.txt
D:\Object_casedocs\C132.txt
D:\Object_casedocs\C1320.txt
D:\Object_casedocs\C1321.txt
D:\Object_casedocs\C1322.txt
D:\Object_casedocs\C1323.txt
D:\Object_casedocs\C1324.txt
D:\Object_casedocs\C1325.txt
D:\Object_casedocs\C1326.txt
D:\Object_casedocs\C1327.txt
D:\Object_casedocs\C1328.txt
D:\Object_casedocs\C1329.txt
D:\Object_casedocs\C133.txt
D:\Object_casedocs\C1330.txt
D:\Object_casedocs\C1331.txt
D:\Object_casedocs\C1332.txt
D:\Object_casedocs\C1333.txt
D:\Object_casedocs\C1334.txt
D:\Object_casedocs\C1335.txt
D:\Object_casedocs\C1336.txt
D:\Object_casedocs\C1337.txt
D:\Object_casedocs\C1338.txt
D:\Object_casedocs\C1339.txt
D:\Object_casedocs\C134.txt
D:\Object_casedocs\C1340.txt
D:\Object_casedocs\C1341.txt
D:\Object_casedocs\C1342.txt
D:\Object_casedocs\C1343.txt
D:\Object_casedocs\C1344.txt
D:\Object_casedocs\C1345.txt
D:\Object_casedocs\C1346.txt
D:\Object_casedocs\C1347.txt
D:\Object_casedocs\C1348.txt
D:\Object_casedocs\C1349.txt
D:\Object_casedocs\C135.txt
D:\Object_casedocs\C1350.txt
D:\Object_casedocs\C1351.txt
D:\Object_casedocs\C1352.txt
D:\Object_casedocs\C1353.txt
D:\Object_casedocs\C1354.txt
D:\Object_casedocs\C1355.txt
D:\Object_casedocs\C1356.txt
D:\Object_casedocs\C1357.txt
D:\Object_casedocs\C1358.txt
D:\Object_casedocs\C1359.txt
D:\Object_casedocs\C136.txt
D:\Object_casedocs\C1360.txt
D:\Object_casedocs\C1361.txt
D:\Object_casedocs\C1362.txt
D:\Object_casedocs\C1363.txt
D:\Object_casedocs\C1364.txt
D:\Object_casedocs\C1365.txt
D:\Object_casedocs\C1366.txt
D:\Object_casedocs\C1367.txt
D:\Object_casedocs\C1368.txt
D:\Object_casedocs\C1369.txt
D:\Object_casedocs\C137.txt
D:\Object_casedocs\C1370.txt
D:\Object_casedocs\C1371.txt
D:\Object_casedocs\C1372.txt
D:\Object_casedocs\C1373.txt
D:\Object_casedocs\C1374.txt
D:\Object_casedocs\C1375.txt
D:\Object_casedocs\C1376.txt
D:\Object_casedocs\C1377.txt
D:\Object_casedocs\C1378.txt
D:\Object_casedocs\C1379.txt
D:\Object_casedocs\C138.txt
D:\Object_casedocs\C1380.txt
D:\Object_casedocs\C1381.txt
D:\Object_casedocs\C1382.txt
D:\Object_casedocs\C1383.txt
D:\Object_casedocs\C1384.txt
D:\Object_casedocs\C1385.txt
D:\Object_casedocs\C1386.txt
D:\Object_casedocs\C1387.txt
D:\Object_casedocs\C1388.txt
D:\Object_casedocs\C1389.txt
D:\Object_casedocs\C139.txt
D:\Object_casedocs\C1390.txt
D:\Object_casedocs\C1391.txt
D:\Object_casedocs\C1392.txt
D:\Object_casedocs\C1393.txt
D:\Object_casedocs\C1394.txt
D:\Object_casedocs\C1395.txt
D:\Object_casedocs\C1396.txt
D:\Object_casedocs\C1397.txt
D:\Object_casedocs\C1398.txt
D:\Object_casedocs\C1399.txt
D:\Object_casedocs\C14.txt
D:\Object_casedocs\C140.txt
D:\Object_casedocs\C1400.txt
D:\Object_casedocs\C1401.txt
D:\Object_casedocs\C1402.txt
D:\Object_casedocs\C1403.txt
D:\Object_casedocs\C1404.txt
D:\Object_casedocs\C1405.txt
D:\Object_casedocs\C1406.txt
D:\Object_casedocs\C1407.txt
D:\Object_casedocs\C1408.txt
D:\Object_casedocs\C1409.txt
D:\Object_casedocs\C141.txt
D:\Object_casedocs\C1410.txt
D:\Object_casedocs\C1411.txt
D:\Object_casedocs\C1412.txt
D:\Object_casedocs\C1413.txt
D:\Object_casedocs\C1414.txt
D:\Object_casedocs\C1415.txt
D:\Object_casedocs\C1416.txt
D:\Object_casedocs\C1417.txt
D:\Object_casedocs\C1418.txt
D:\Object_casedocs\C1419.txt
D:\Object_casedocs\C142.txt
D:\Object_casedocs\C1420.txt
D:\Object_casedocs\C1421.txt
D:\Object_casedocs\C1422.txt
D:\Object_casedocs\C1423.txt
D:\Object_casedocs\C1424.txt
D:\Object_casedocs\C1425.txt
D:\Object_casedocs\C1426.txt
D:\Object_casedocs\C1427.txt
D:\Object_casedocs\C1428.txt
D:\Object_casedocs\C1429.txt
D:\Object_casedocs\C143.txt
D:\Object_casedocs\C1430.txt
D:\Object_casedocs\C1431.txt
D:\Object_casedocs\C1432.txt
D:\Object_casedocs\C1433.txt
D:\Object_casedocs\C1434.txt
D:\Object_casedocs\C1435.txt
D:\Object_casedocs\C1436.txt
D:\Object_casedocs\C1437.txt
D:\Object_casedocs\C1438.txt
D:\Object_casedocs\C1439.txt
D:\Object_casedocs\C144.txt
D:\Object_casedocs\C1440.txt
D:\Object_casedocs\C1441.txt
D:\Object_casedocs\C1442.txt
D:\Object_casedocs\C1443.txt
D:\Object_casedocs\C1444.txt
D:\Object_casedocs\C1445.txt
D:\Object_casedocs\C1446.txt
D:\Object_casedocs\C1447.txt
D:\Object_casedocs\C1448.txt
D:\Object_casedocs\C1449.txt
D:\Object_casedocs\C145.txt
D:\Object_casedocs\C1450.txt
D:\Object_casedocs\C1451.txt
D:\Object_casedocs\C1452.txt
D:\Object_casedocs\C1453.txt
D:\Object_casedocs\C1454.txt
D:\Object_casedocs\C1455.txt
D:\Object_casedocs\C1456.txt
D:\Object_casedocs\C1457.txt
D:\Object_casedocs\C1458.txt
D:\Object_casedocs\C1459.txt
D:\Object_casedocs\C146.txt
D:\Object_casedocs\C1460.txt
D:\Object_casedocs\C1461.txt
D:\Object_casedocs\C1462.txt
D:\Object_casedocs\C1463.txt
D:\Object_casedocs\C1464.txt
D:\Object_casedocs\C1465.txt
D:\Object_casedocs\C1466.txt
D:\Object_casedocs\C1467.txt
D:\Object_casedocs\C1468.txt
D:\Object_casedocs\C1469.txt
D:\Object_casedocs\C147.txt
D:\Object_casedocs\C1470.txt
D:\Object_casedocs\C1471.txt
D:\Object_casedocs\C1472.txt
D:\Object_casedocs\C1473.txt
D:\Object_casedocs\C1474.txt
D:\Object_casedocs\C1475.txt
D:\Object_casedocs\C1476.txt
D:\Object_casedocs\C1477.txt
D:\Object_casedocs\C1478.txt
D:\Object_casedocs\C1479.txt
D:\Object_casedocs\C148.txt
D:\Object_casedocs\C1480.txt
D:\Object_casedocs\C1481.txt
D:\Object_casedocs\C1482.txt
D:\Object_casedocs\C1483.txt
D:\Object_casedocs\C1484.txt
D:\Object_casedocs\C1485.txt
D:\Object_casedocs\C1486.txt
D:\Object_casedocs\C1487.txt
D:\Object_casedocs\C1488.txt
D:\Object_casedocs\C1489.txt
D:\Object_casedocs\C149.txt
D:\Object_casedocs\C1490.txt
D:\Object_casedocs\C1491.txt
D:\Object_casedocs\C1492.txt
D:\Object_casedocs\C1493.txt
D:\Object_casedocs\C1494.txt
D:\Object_casedocs\C1495.txt
D:\Object_casedocs\C1496.txt
D:\Object_casedocs\C1497.txt
D:\Object_casedocs\C1498.txt
D:\Object_casedocs\C1499.txt
D:\Object_casedocs\C15.txt
D:\Object_casedocs\C150.txt
D:\Object_casedocs\C1500.txt
D:\Object_casedocs\C1501.txt
D:\Object_casedocs\C1502.txt
D:\Object_casedocs\C1503.txt
D:\Object_casedocs\C1504.txt
D:\Object_casedocs\C1505.txt
D:\Object_casedocs\C1506.txt
D:\Object_casedocs\C1507.txt
D:\Object_casedocs\C1508.txt
D:\Object_casedocs\C1509.txt
D:\Object_casedocs\C151.txt
D:\Object_casedocs\C1510.txt
D:\Object_casedocs\C1511.txt
D:\Object_casedocs\C1512.txt
D:\Object_casedocs\C1513.txt
D:\Object_casedocs\C1514.txt
D:\Object_casedocs\C1515.txt
D:\Object_casedocs\C1516.txt
D:\Object_casedocs\C1517.txt
D:\Object_casedocs\C1518.txt
D:\Object_casedocs\C1519.txt
D:\Object_casedocs\C152.txt
D:\Object_casedocs\C1520.txt
D:\Object_casedocs\C1521.txt
D:\Object_casedocs\C1522.txt
D:\Object_casedocs\C1523.txt
D:\Object_casedocs\C1524.txt
D:\Object_casedocs\C1525.txt
D:\Object_casedocs\C1526.txt
D:\Object_casedocs\C1527.txt
D:\Object_casedocs\C1528.txt
D:\Object_casedocs\C1529.txt
D:\Object_casedocs\C153.txt
D:\Object_casedocs\C1530.txt
D:\Object_casedocs\C1531.txt
D:\Object_casedocs\C1532.txt
D:\Object_casedocs\C1533.txt
D:\Object_casedocs\C1534.txt
D:\Object_casedocs\C1535.txt
D:\Object_casedocs\C1536.txt
D:\Object_casedocs\C1537.txt
D:\Object_casedocs\C1538.txt
D:\Object_casedocs\C1539.txt
D:\Object_casedocs\C154.txt
D:\Object_casedocs\C1540.txt
D:\Object_casedocs\C1541.txt
D:\Object_casedocs\C1542.txt
D:\Object_casedocs\C1543.txt
D:\Object_casedocs\C1544.txt
D:\Object_casedocs\C1545.txt
D:\Object_casedocs\C1546.txt
D:\Object_casedocs\C1547.txt
D:\Object_casedocs\C1548.txt
D:\Object_casedocs\C1549.txt
D:\Object_casedocs\C155.txt
D:\Object_casedocs\C1550.txt
D:\Object_casedocs\C1551.txt
D:\Object_casedocs\C1552.txt
D:\Object_casedocs\C1553.txt
D:\Object_casedocs\C1554.txt
D:\Object_casedocs\C1555.txt
D:\Object_casedocs\C1556.txt
D:\Object_casedocs\C1557.txt
D:\Object_casedocs\C1558.txt
D:\Object_casedocs\C1559.txt
D:\Object_casedocs\C156.txt
D:\Object_casedocs\C1560.txt
D:\Object_casedocs\C1561.txt
D:\Object_casedocs\C1562.txt
D:\Object_casedocs\C1563.txt
D:\Object_casedocs\C1564.txt
D:\Object_casedocs\C1565.txt
D:\Object_casedocs\C1566.txt
D:\Object_casedocs\C1567.txt
D:\Object_casedocs\C1568.txt
D:\Object_casedocs\C1569.txt
D:\Object_casedocs\C157.txt
D:\Object_casedocs\C1570.txt
D:\Object_casedocs\C1571.txt
D:\Object_casedocs\C1572.txt
D:\Object_casedocs\C1573.txt
D:\Object_casedocs\C1574.txt
D:\Object_casedocs\C1575.txt
D:\Object_casedocs\C1576.txt
D:\Object_casedocs\C1577.txt
D:\Object_casedocs\C1578.txt
D:\Object_casedocs\C1579.txt
D:\Object_casedocs\C158.txt
D:\Object_casedocs\C1580.txt
D:\Object_casedocs\C1581.txt
D:\Object_casedocs\C1582.txt
D:\Object_casedocs\C1583.txt
D:\Object_casedocs\C1584.txt
D:\Object_casedocs\C1585.txt
D:\Object_casedocs\C1586.txt
D:\Object_casedocs\C1587.txt
D:\Object_casedocs\C1588.txt
D:\Object_casedocs\C1589.txt
D:\Object_casedocs\C159.txt
D:\Object_casedocs\C1590.txt
D:\Object_casedocs\C1591.txt
D:\Object_casedocs\C1592.txt
D:\Object_casedocs\C1593.txt
D:\Object_casedocs\C1594.txt
D:\Object_casedocs\C1595.txt
D:\Object_casedocs\C1596.txt
D:\Object_casedocs\C1597.txt
D:\Object_casedocs\C1598.txt
D:\Object_casedocs\C1599.txt
D:\Object_casedocs\C16.txt
D:\Object_casedocs\C160.txt
D:\Object_casedocs\C1600.txt
D:\Object_casedocs\C1601.txt
D:\Object_casedocs\C1602.txt
D:\Object_casedocs\C1603.txt
D:\Object_casedocs\C1604.txt
D:\Object_casedocs\C1605.txt
D:\Object_casedocs\C1606.txt
D:\Object_casedocs\C1607.txt
D:\Object_casedocs\C1608.txt
D:\Object_casedocs\C1609.txt
D:\Object_casedocs\C161.txt
D:\Object_casedocs\C1610.txt
D:\Object_casedocs\C1611.txt
D:\Object_casedocs\C1612.txt
D:\Object_casedocs\C1613.txt
D:\Object_casedocs\C1614.txt
D:\Object_casedocs\C1615.txt
D:\Object_casedocs\C1616.txt
D:\Object_casedocs\C1617.txt
D:\Object_casedocs\C1618.txt
D:\Object_casedocs\C1619.txt
D:\Object_casedocs\C162.txt
D:\Object_casedocs\C1620.txt

In [46]:
import glob
import csv

read_files = glob.glob('D:\Object_casedocs\*')

with open("casedocs.csv", "w") as outfile:
    w=csv.writer(outfile)
    for f in read_files:
        with open(f, "r") as infile:
            w.writerow([" ".join([line.strip() for line in infile])])

In [47]:
df = pd.read_csv('casedocs.csv',header=None)
df.columns = ["Text"]
df

                                                   Text
0     Masud Khan v State Of Uttar Pradesh Supreme Co...
1     Prabhakaran Nair, Etc. v State Of Tamil Nadu A...
2     Hiten P. Dalal v Bratindranath Banerjee Suprem...
3     Ashok Kumar and Others v State of Tamil Nadu S...
4     Ashok Dhingra v N.C.T. of Delhi Supreme Court ...
...                                                 ...
2909  Rajendra Singh v State of Uttaranchal Supreme ...
2910  Food Corporation Of India & Anr v Seil Ltd. & ...
2911  State of Kerala v Sasi Supreme Court of India ...
2912  Columbia Sportswear Company v Director Of Inco...
2913  Bharat Gurjar and others v State of Rajasthan ...

[2914 rows x 1 columns]

In [48]:
z=[]
for i in range(2914):
    z.append(df.Text[i])

In [49]:
jud=[]
for c in z:
    for j in range(len(c.split())):
        p=c.split()
        if p[j] =="India" and p[j-2]=="Court":
            q=str(p[j+1])+ " "+str(p[j+2])+" "+str(p[j+3])
            jud.append(q)
            break

In [50]:
jud

['26 September 1973',
 '3 September 1987',
 '11 July 2001',
 '5 May 2006',
 '3 March 2000',
 '11 September 1962',
 '7 September 2010',
 '17 January 1968',
 '25 November 1959',
 '6 August 1982',
 '11 August 2003',
 '25 January 2000',
 '7 October 1994',
 '10 August 1999',
 '4 May 2009',
 '14 January 1992',
 '30 January 2012',
 '23 November 2006',
 '30 August 2007',
 '19 April 2004',
 '24 April 2002',
 '22 August 1969',
 '3 March 1971',
 '29 January 1975',
 '6 December 1960',
 '10 January 2005',
 '8 July 2010',
 '19 July 2011',
 '23 February 1970',
 '30 October 2001',
 '1 April 1998',
 '16 August 2010',
 '12 August 2014',
 '23 February 1971',
 '3 March 2005',
 '4 November 1997',
 '31 October 2003',
 '12 September 1978',
 '17 December 2003',
 '22 March 2013',
 '11 August 2005',
 '30 October 1969',
 '13 February 1980',
 '13 December 2012',
 '2 January 2017',
 '19 February 2007',
 '26 September 2003',
 '24 April 2009',
 '29 November 1991',
 '5 October 2005',
 '11 May 2005',
 '3 October 1979',
 '9 May 2008',
 '31 July 2003',
 '2 May 2017',
 '31 March 2009',
 '14 March 1972',
 '12 April 2004',
 '14 November 2011',
 '12 May 2011',
 '6 November 2006',
 '2 July 2014',
 '24 January 2002',
 '7 October 1969',
 '5 November 1971',
 '17 September 2002',
 '29 March 2000',
 '30 July 1992',
 '10 December 1999',
 '8 May 2009',
 '21 August 1995',
 '16 January 1987',
 '28 July 1999',
 '14 September 2006',
 '26 August 2003',
 '7 May 1996',
 '8 February 1972',
 '14 September 1976',
 '26 April 1974',
 '5 March 1998',
 '8 March 1989',
 '16 December 2011',
 '19 April 1961',
 '27 February 2009',
 '2 May 1977',
 '21 February 1983',
 '7 January 1997',
 '3 September 1998',
 '24 January 2002',
 '13 March 1990',
 '18 September 1987',
 '4 November 1982',
 '22 November 2004',
 '10 February 2011',
 '15 October 2003',
 '6 May 2009',
 '4 March 2014',
 '21 August 1990',
 '30 November 1978',
 '18 January 1994',
 '15 December 2014',
 '7 August 1990',
 '29 September 2008',
 '4 July 2016',
 '27 March 2014',
 '13 February 1976',
 '29 September 1967',
 '28 February 1974',
 '8 August 2008',
 '27 January 2000',
 '9 March 2010',
 '12 April 1979',
 '9 July 1996',
 '6 November 1990',
 '25 April 2005',
 '27 April 2004',
 '2 May 2008',
 '29 January 2002',
 '25 November 2003',
 '14 February 1991',
 '10 February 2004',
 '28 November 2014',
 '27 January 1975',
 '27 November 1996',
 '29 August 1989',
 '20 January 2011',
 '18 July 1972',
 '5 February 2014',
 '12 April 1999',
 '12 November 2014',
 '9 October 1969',
 '20 August 1964',
 '7 February 1958',
 '3 April 1967',
 '7 March 1962',
 '26 October 1998',
 '26 September 2008',
 '13 December 2007',
 '18 September 2003',
 '9 February 1990',
 '10 March 1983',
 '18 July 2006',
 '1 July 2015',
 '28 November 2006',
 '6 September 1974',
 '13 August 1998',
 '28 March 2008',
 '24 July 2001',
 '5 January 1998',
 '6 March 1992',
 '9 January 1991',
 '7 May 2010',
 '10 May 2012',
 '16 January 1969',
 '22 March 2012',
 '30 July 2010',
 '6 April 1989',
 '20 December 1991',
 '20 February 2017',
 '1 August 2002',
 '11 March 2003',
 '4 February 2013',
 '6 May 1996',
 '20 March 2009',
 '7 October 2009',
 '12 April 2016',
 '6 May 2009',
 '21 February 1978',
 '19 November 1963',
 '1 September 2014',
 '26 April 2013',
 '3 March 2008',
 '6 November 1990',
 '17 April 2009',
 '8 October 2004',
 '14 July 1993',
 '2 September 2005',
 '2 February 2017',
 '12 February 1987',
 '25 August 1988',
 '8 May 2014',
 '15 September 2016',
 '3 October 1979',
 '15 January 2015',
 '4 January 2008',
 '31 January 1979',
 '31 August 1989',
 '17 November 2003',
 '15 October 1992',
 '25 February 2014',
 '31 July 1996',
 '26 March 2009',
 '7 November 2006',
 '22 July 2003',
 '2 August 2005',
 '18 July 2016',
 '12 March 1992',
 '15 January 1971',
 '3 May 1989',
 '11 January 1991',
 '9 March 1981',
 '5 April 2002',
 '28 November 2008',
 '29 May 2009',
 '17 December 1999',
 '3 July 2013',
 '6 October 2009',
 '29 September 1994',
 '15 January 2002',
 '15 September 2010',
 '11 September 2001',
 '25 March 2014',
 '10 May 1985',
 '17 June 2009',
 '27 February 2002',
 '9 February 2009',
 '18 November 2004',
 '4 December 1992',
 '27 August 2003',
 '31 July 2009',
 '3 July 2006',
 '13 November 1980',
 '6 January 1999',
 '2 May 1989',
 '13 March 1953',
 '13 March 1975',
 '1 February 2010',
 '16 September 2014',
 '14 March 2008',
 '18 April 2000',
 '10 January 1957',
 '15 September 2010',
 '29 August 2002',
 '22 October 1991',
 '12 May 1995',
 '25 August 1988',
 '25 September 2001',
 '12 December 2002',
 '2 February 2007',
 '28 November 2014',
 '29 August 2000',
 '15 January 2015',
 '3 November 1992',
 '19 October 2001',
 '23 February 1993',
 '3 February 1993',
 '27 August 2002',
 '14 September 1978',
 '24 January 2013',
 '18 November 2003',
 '5 March 1980',
 '19 November 2010',
 '4 February 2004',
 '5 May 1954',
 '8 August 1979',
 '5 November 2008',
 '22 August 1968',
 '16 December 2010',
 '9 July 1991',
 '16 November 2006',
 '22 February 1974',
 '2 July 2014',
 '5 May 1989',
 '31 October 1972',
 '1 March 1971',
 '20 August 2007',
 '26 November 2010',
 '21 August 1997',
 '8 May 1998',
 '20 October 2008',
 '7 November 2008',
 '23 February 2018',
 '10 August 1994',
 '5 May 2004',
 '25 August 2009',
 '14 December 1971',
 '31 October 2002',
 '25 July 2001',
 '22 July 1998',
 '9 September 1996',
 '5 May 2008',
 '15 January 1999',
 '27 March 2009',
 '24 January 1983',
 '16 August 2012',
 '21 March 1996',
 '14 May 1999',
 '3 January 2017',
 '9 December 2014',
 '22 August 1984',
 '11 May 1988',
 '16 February 1983',
 '20 October 2005',
 '21 April 2009',
 '29 July 1998',
 '11 July 1996',
 '31 January 1968',
 '12 March 1969',
 '12 March 2014',
 '29 September 2006',
 '3 February 1964',
 '16 November 2006',
 '12 October 2012',
 '27 January 1965',
 '5 May 1993',
 '9 January 1973',
 '15 July 2003',
 '9 April 1980',
 '14 September 2012',
 '9 May 1980',
 '16 October 2008',
 '24 February 1988',
 '12 July 1996',
 '25 November 1997',
 '28 July 2009',
 '6 October 2016',
 '22 September 1967',
 '24 November 2003',
 '9 February 1988',
 '21 August 2002',
 '12 February 2008',
 '27 August 1991',
 '8 November 2000',
 '14 December 2004',
 '8 January 2007',
 '6 November 1979',
 '31 October 1991',
 '27 September 2004',
 '29 January 1976',
 '31 October 2001',
 '21 October 2008',
 '15 October 2008',
 '20 January 2003',
 '3 September 2004',
 '26 April 1999',
 '18 January 1979',
 '24 August 2006',
 '5 December 1975',
 '10 August 1978',
 '13 August 1974',
 '13 February 2001',
 '14 August 2001',
 '12 January 2010',
 '13 January 2004',
 '1 May 2001',
 '8 December 1999',
 '28 July 1981',
 '20 September 1996',
 '10 April 2017',
 '26 July 2010',
 '3 March 1965',
 '23 August 2004',
 '18 October 2012',
 '5 October 1972',
 '7 November 2008',
 '30 July 2014',
 '26 November 1954',
 '12 August 1981',
 '20 January 2006',
 '29 April 2004',
 '28 November 2008',
 '12 January 2009',
 '11 March 2015',
 '5 February 2004',
 '16 January 2009',
 '7 April 1960',
 '22 April 2016',
 '15 March 2004',
 '25 January 1961',
 '6 December 2006',
 '30 March 1971',
 '3 September 1980',
 '2 August 2000',
 '5 November 1993',
 '15 February 2007',
 '17 October 2013',
 '8 March 1988',
 '24 March 2009',
 '12 November 2002',
 '12 May 1999',
 '11 May 2015',
 '6 February 1998',
 '6 May 2010',
 '11 August 1992',
 '26 April 2013',
 '29 January 1964',
 '5 May 2017',
 '14 March 2008',
 '18 September 2006',
 '28 March 2000',
 '15 November 1989',
 '11 September 1979',
 '9 July 2008',
 '2 September 2003',
 '1 November 2002',
 '30 October 1981',
 '19 March 2002',
 '23 August 1996',
 '31 January 2003',
 '20 August 2008',
 '3 July 2013',
 '10 May 1988',
 '23 May 2014',
 '28 April 2006',
 '25 August 2011',
 '11 April 1988',
 '3 May 2007',
 '5 February 1988',
 '4 April 1977',
 '22 April 1992',
 '10 October 2007',
 '15 May 2009',
 '9 June 2011',
 '20 January 2015',
 '2 September 2014',
 '3 March 2016',
 '16 October 2012',
 '5 March 2008',
 '8 July 1997',
 '1 September 2010',
 '5 December 1995',
 '16 May 1957',
 '2 February 1993',
 '3 March 2005',
 '4 December 2006',
 '13 August 2010',
 '18 December 1992',
 '16 April 2015',
 '13 October 2008',
 '12 February 1996',
 '5 April 1956',
 '13 April 2005',
 '9 September 2002',
 '10 August 2010',
 '23 August 1971',
 '12 December 1962',
 '22 October 1963',
 '27 April 1998',
 '24 July 2009',
 '10 October 1990',
 '8 February 2010',
 '23 March 1976',
 '18 March 1964',
 '3 April 2001',
 '14 February 2008',
 '6 April 1986',
 '11 January 2008',
 '15 February 2018',
 '17 February 2003',
 '6 April 2004',
 '1 December 2015',
 '27 February 2003',
 '8 January 1994',
 '30 August 1978',
 '26 February 2007',
 '8 August 1962',
 '11 November 2009',
 '6 December 2006',
 '14 May 2010',
 '11 March 2011',
 '20 November 1987',
 '18 September 1973',
 '31 March 2009',
 '13 March 2015',
 '20 August 1981',
 '19 November 2008',
 '16 January 1979',
 '11 August 1987',
 '24 February 2014',
 '2 March 2017',
 '5 February 2004',
 '7 July 2011',
 '29 October 2001',
 '13 October 1992',
 '4 November 1964',
 '6 July 2010',
 '3 August 2012',
 '25 August 2015',
 '21 June 2007',
 '28 August 1992',
 '16 September 1965',
 '13 May 2009',
 '11 September 2003',
 '17 October 2008',
 '22 January 2015',
 '9 January 2008',
 '12 February 1957',
 '23 October 1992',
 '11 January 2008',
 '25 March 2009',
 '18 December 2008',
 '28 November 2003',
 '13 August 1998',
 '13 December 2006',
 '26 November 1959',
 '9 October 2015',
 '1 September 2008',
 '30 March 1987',
 '6 November 1990',
 '7 February 2007',
 '6 September 1995',
 '14 December 1998',
 '8 November 2005',
 '7 April 1993',
 '15 July 2008',
 '15 July 2013',
 '17 December 1996',
 '4 April 1962',
 '6 February 2017',
 '2 May 1990',
 '14 July 1994',
 '13 August 2002',
 '1 November 1955',
 '3 August 1995',
 '13 January 2009',
 '20 February 1981',
 '3 April 2007',
 '14 August 2001',
 '7 March 2011',
 '14 January 1992',
 '27 April 2007',
 '26 August 1993',
 '8 September 2017',
 '31 March 1981',
 '28 July 1966',
 '24 August 2017',
 '21 January 2000',
 '24 January 1972',
 '16 April 1975',
 '9 November 2000',
 '28 July 2015',
 '25 January 1995',
 '9 May 2013',
 '24 April 2017',
 '5 March 1998',
 '8 December 2004',
 '10 October 1969',
 '6 April 1962',
 '5 February 1997',
 '22 September 1999',
 '31 March 2009',
 '4 October 2013',
 '7 September 2007',
 '26 February 2008',
 '31 January 2017',
 '8 April 1965',
 '9 November 1989',
 '2 September 1997',
 '6 September 2005',
 '6 January 2006',
 '12 November 2002',
 '10 February 1993',
 '12 December 2000',
 '16 September 2003',
 '26 March 1980',
 '15 October 2015',
 '23 January 2003',
 '12 March 1999',
 '2 December 2008',
 '24 August 1976',
 '26 October 1987',
 '26 February 1998',
 '23 April 1971',
 '7 March 1972',
 '20 April 1977',
 '9 May 2000',
 '9 May 2014',
 '15 January 2008',
 '16 September 2014',
 '15 September 2006',
 '8 May 2012',
 '21 February 1978',
 '9 February 2017',
 '7 January 2003',
 '26 October 2010',
 '4 April 1989',
 '19 February 2013',
 '28 February 1979',
 '24 July 2008',
 '15 May 2013',
 '22 November 2012',
 '20 February 2007',
 '13 May 2005',
 '1 October 1991',
 '13 April 2004',
 '11 October 2011',
 '9 November 1990',
 '29 October 2002',
 '23 July 1968',
 '29 March 2005',
 '30 March 1993',
 '17 September 2004',
 '18 December 1992',
 '24 November 2004',
 '4 October 1991',
 '22 July 2010',
 '18 January 1994',
 '1 November 2006',
 '15 October 2008',
 '27 September 2010',
 '8 November 1996',
 '29 September 1999',
 '24 November 2004',
 '9 May 1996',
 '18 March 1976',
 '19 August 1976',
 '2 November 2007',
 '21 August 2003',
 '23 May 2014',
 '13 October 2003',
 '4 September 2002',
 '8 July 2010',
 '14 December 2012',
 '22 April 2008',
 '21 January 1998',
 '4 July 2011',
 '3 August 2017',
 '15 April 1998',
 '7 November 2008',
 '24 October 2013',
 '20 February 1987',
 '13 May 1998',
 '17 March 2015',
 '15 April 1982',
 '11 November 1980',
 '1 November 1996',
 '9 February 2016',
 '4 December 2003',
 '5 September 1972',
 '18 March 2004',
 '23 February 2017',
 '9 August 2016',
 '20 February 1987',
 '12 May 2006',
 '17 February 2010',
 '23 August 1990',
 '20 July 2004',
 '15 February 1996',
 '24 May 1954',
 '18 July 2014',
 '16 January 2012',
 '5 May 1988',
 '2 September 2015',
 '12 February 2009',
 '12 May 2008',
 '7 May 2002',
 '1 May 2017',
 '6 August 2013',
 '14 May 2007',
 '16 September 2005',
 '9 May 2007',
 '23 July 1998',
 '15 February 2002',
 '12 August 2016',
 '25 March 1964',
 '15 October 2008',
 '16 August 1974',
 '8 April 1991',
 '6 March 1987',
 '31 January 1968',
 '18 October 2000',
 '24 February 1988',
 '11 March 2013',
 '27 February 1986',
 '2 July 2014',
 '4 September 2000',
 '1 August 2003',
 '11 March 1983',
 '19 October 2006',
 '26 April 1996',
 '23 July 1993',
 '16 November 1994',
 '3 February 2001',
 '31 July 2000',
 '16 October 2015',
 '15 May 2015',
 '3 February 2015',
 '8 August 2002',
 '21 April 2009',
 '17 April 1990',
 '15 December 2017',
 '15 February 2008',
 '8 August 1989',
 '10 April 1987',
 '3 September 2014',
 '23 August 1996',
 '20 July 1983',
 '18 April 1969',
 '16 November 1962',
 '10 September 2008',
 '31 January 2012',
 '6 December 2006',
 '10 December 2002',
 '6 July 2009',
 '29 May 2012',
 '7 October 2003',
 '23 February 1981',
 '17 December 2003',
 '13 August 1984',
 '21 April 1987',
 '2 December 2008',
 '12 April 2004',
 '27 March 2006',
 '4 September 1981',
 '21 January 1975',
 '15 July 1999',
 '20 January 2014',
 '17 April 1980',
 '1 October 2007',
 '12 December 1960',
 '10 April 1990',
 '27 March 1997',
 '5 September 1972',
 '29 November 2016',
 '4 December 1995',
 '2 April 2013',
 '27 September 2000',
 '24 January 2000',
 '27 July 2010',
 '22 August 1983',
 '5 April 1967',
 '28 August 2012',
 '17 November 2009',
 '19 March 1996',
 '16 May 2008',
 '3 December 2012',
 '11 September 2001',
 '4 April 1989',
 '24 July 2013',
 '8 August 1961',
 '23 July 1968',
 '11 April 2017',
 '25 November 1988',
 '18 September 1996',
 '26 September 1955',
 '12 May 2006',
 '20 November 2003',
 '29 October 1999',
 '1 November 1995',
 '12 September 2000',
 '6 February 1996',
 '7 December 2010',
 '30 November 1995',
 '11 December 2014',
 '11 April 2017',
 '11 May 2010',
 '2 September 2011',
 '21 January 2008',
 '11 December 2013',
 '9 October 1990',
 '14 January 2002',
 '9 August 2012',
 '2 April 2013',
 '20 July 2011',
 '9 January 2009',
 '3 November 1961',
 '15 January 2003',
 '6 November 2009',
 '13 May 2015',
 '14 August 2013',
 '3 May 1990',
 '16 March 1961',
 '1 October 2013',
 '18 November 2008',
 '7 September 2001',
 '11 December 2012',
 '13 February 2013',
 '17 July 1984',
 '19 August 2004',
 '2 February 1996',
 '7 April 1993',
 '4 May 2007',
 '22 February 1995',
 '3 September 2002',
 '6 August 1998',
 '20 April 2009',
 '23 July 2002',
 '11 May 1994',
 '20 April 2004',
 '16 December 1993',
 '28 November 2016',
 '21 March 1995',
 '6 October 1978',
 '8 May 2009',
 '22 August 1984',
 '29 April 1998',
 '14 July 1998',
 '5 March 2003',
 '15 March 1954',
 '2 November 1999',
 '12 May 1993',
 '3 September 1993',
 '15 November 1995',
 '27 April 2007',
 '28 July 1994',
 '26 October 2016',
 '14 May 1992',
 '30 March 1995',
 '25 February 2009',
 '15 September 1999',
 '21 May 2013',
 '14 September 2006',
 '14 February 2007',
 '3 June 2014',
 '16 October 2012',
 '15 February 1993',
 '1 November 1966',
 '30 July 2012',
 '13 November 2007',
 '13 August 2002',
 '5 April 2006',
 '18 September 2008',
 '22 March 2002',
 '9 October 2002',
 '20 January 2004',
 '9 November 1984',
 '17 October 1969',
 '12 October 2007',
 '27 October 1994',
 '29 March 1994',
 '24 January 1963',
 '24 September 1959',
 '22 November 1991',
 '14 March 2005',
 '9 March 1962',
 '23 September 2008',
 '14 October 2004',
 '1 May 1975',
 '26 July 2007',
 '9 February 2009',
 '15 February 1977',
 '25 April 2005',
 '3 April 2008',
 '7 February 1975',
 '23 August 1989',
 '11 March 2008',
 '23 May 1984',
 '17 August 2006',
 '28 April 1998',
 '25 February 2014',
 '7 September 2005',
 '28 May 2009',
 '18 November 2008',
 '20 October 2009',
 '30 March 2010',
 '17 August 1970',
 '8 August 1997',
 '3 October 2016',
 '18 March 2002',
 '8 January 2007',
 '10 October 1979',
 '19 January 2016',
 '23 July 2002',
 '30 July 1984',
 '1 October 1999',
 '14 October 2004',
 '22 July 2002',
 '9 February 1959',
 '23 August 1989',
 '16 November 2000',
 '26 March 1991',
 '7 May 2013',
 '13 February 1970',
 '19 September 1988',
 '9 January 2001',
 '27 November 2003',
 '7 November 1975',
 '30 March 1993',
 '25 February 2009',
 '9 August 1989',
 '21 November 2012',
 '17 November 1972',
 '12 March 1992',
 '31 October 2006',
 '6 February 2012',
 '28 August 1962',
 '14 April 1981',
 '26 February 1999',
 '11 August 1987',
 '13 August 1976',
 '17 October 1978',
 '4 September 2008',
 '2 August 2007',
 '12 April 2007',
 '7 October 1964',
 '10 July 2012',
 '2 December 1981',
 '9 November 2016',
 '8 March 2007',
 '30 April 2004',
 '22 April 1963',
 '5 January 2017',
 '1 May 2001',
 '23 November 2004',
 '24 April 2009',
 '9 July 2013',
 '25 September 2014',
 '30 November 2012',
 '7 February 1994',
 '16 August 1988',
 '3 February 1998',
 '13 November 1992',
 '13 September 1956',
 '22 January 1987',
 '12 February 2015',
 '1 August 1989',
 '7 August 2002',
 '25 September 1997',
 '23 April 2002',
 '29 November 2002',
 '3 September 2009',
 '23 February 2001',
 '5 May 1993',
 '17 October 2001',
 '8 March 2000',
 'and Another Supreme',
 '30 January 1974',
 '24 February 2006',
 '30 March 1990',
 '9 April 2009',
 '5 April 2013',
 '12 January 2009',
 '3 September 1997',
 '19 April 1963',
 '7 July 1983',
 '22 September 2000',
 '28 November 2007',
 '20 March 2006',
 '4 May 2009',
 '5 April 2004',
 '14 October 1977',
 '23 November 2007',
 '4 September 1992',
 '12 March 1981',
 '18 September 1981',
 '7 December 2015',
 '13 October 1958',
 '27 September 2010',
 '17 August 1995',
 '9 February 2000',
 '2 August 1972',
 '20 January 2009',
 '25 April 2014',
 '31 January 1989',
 '16 October 2015',
 '30 March 1953',
 '17 November 1971',
 '29 March 2011',
 '2 March 2012',
 '4 May 1979',
 '16 April 2015',
 '31 March 2008',
 '29 November 1984',
 '13 December 1960',
 '1 May 1985',
 '1 February 2006',
 '21 May 1959',
 '22 September 1978',
 '26 April 2000',
 '13 July 2001',
 '17 March 2011',
 '19 March 1993',
 '8 April 2004',
 '30 November 1960',
 '9 December 1959',
 '14 October 2014',
 '7 November 1975',
 '25 July 1962',
 '9 August 1999',
 '12 June 2016',
 '13 September 1968',
 '12 November 1980',
 '19 January 1970',
 '21 October 2008',
 '1 October 1997',
 '9 May 2007',
 '15 September 2015',
 '17 December 2008',
 '11 January 1993',
 '30 November 1999',
 '13 February 2009',
 '23 September 2014',
 '29 January 1963',
 '7 October 2013',
 '7 April 1981',
 '15 December 2003',
 '25 February 2011',
 '20 February 2014',
 '2 September 1962',
 '9 July 1997',
 '16 March 2004',
 '13 July 1993',
 '21 September 2006',
 '8 September 1999',
 '6 January 2010',
 '13 July 1993',
 '14 April 1961',
 '29 April 2003',
 '24 July 1972',
 '9 January 2015',
 ...]

In [51]:
df['Start']=jud
print(df)

                                                   Text              Start
0     Masud Khan v State Of Uttar Pradesh Supreme Co...  26 September 1973
1     Prabhakaran Nair, Etc. v State Of Tamil Nadu A...   3 September 1987
2     Hiten P. Dalal v Bratindranath Banerjee Suprem...       11 July 2001
3     Ashok Kumar and Others v State of Tamil Nadu S...         5 May 2006
4     Ashok Dhingra v N.C.T. of Delhi Supreme Court ...       3 March 2000
...                                                 ...                ...
2909  Rajendra Singh v State of Uttaranchal Supreme ...      11 April 2013
2910  Food Corporation Of India & Anr v Seil Ltd. & ...    11 January 2008
2911  State of Kerala v Sasi Supreme Court of India ...    31 October 1996
2912  Columbia Sportswear Company v Director Of Inco...       30 July 2012
2913  Bharat Gurjar and others v State of Rajasthan ...       9 March 2017

[2914 rows x 2 columns]

In [52]:
f=[]
for c in z:
    index=0
    for j in range(len(c.split())):
        index+=1
        if index>=len(c.split()):
            f.append('0')
            continue
        p=c.split()
        if (p[j] =="No." or p[j]=="No"):
            print(p[j+3])
            f.append(p[j+3])
            break

1973
1986
why
2004)
2000.
1962
2010
1967.
1981
&
1995.
1993
1977
2003
1981
make
therefore,
1967.
1968.
1972
1959,
2005
8th
1997
1967
accused
Bhardwaj
2005.
1969
2004
1997
1972
the
2002,
Kant
1966
305/78.
2010
1998
2006)
1996
2009
1990
2003)
1979
2002
2002
of
2004
C.A.
one
2004
2011(Arising
the
2004
2001
1968
1968,
2000
2000
1992
2009
Minister
1998
2002
1996)
to
1971
Chief
1991
1978
2010
1960
2008.
1971
1980
1988
1996
2002
1977
1987
1982
been
2003
Khasra
2009[Arising
2014
1972
1974,
Order
2012
for
2008
2011
2014
1971.
1966
1973
1980
1998
2010
1974.
1995
1974
1998
2006
1977
2014
1974,
1996
1987
1971.
2004
1999
2014
1967
1963.
1957.
1966,
1955
1998
1990
1990
applications
2015
1973.
1998
2008
sanction
Smt.
1979.
1988
2010
held
made
2006
2010)
1979
1991
2013
Ram
1999.
2006,
appellant
allowed
2009
2016
2006
1975
1963.
2009
2008
1979
2001
1999
1988)
2004
2011
State
1987.
2008
the
1979
Judgment
inflicted
1969.
1981
was
1982
(Arising
1995
2004
2005
offence
2005
2014,
1992
1966.
1989
1991
1980.
2008
2004
2007
1987
2002
2004
2008
was
1997
1963
2009
1985
was
receipt
1977.
1983
1978
1971.
the
2014
2006)
1998
the
2010)
2000
1991
75
1999,
1996
deputation
2014
1991
2015
1982
therefore,
1979.
1990
to
1977).
2009)
BACKGROUND;
dated
1988.
1954.
1973.
2007
2005
1987
It
1973
2006
1984.
1972.
1968
2005
1993,
1990
2008
17th
2018
1990
2005
(Transport
1999
2001
1989
1981
1989,
38/98
1982
2009
1995,
1991
Criminal
2014
1981,
368
1983.
The
is
Order
1989,
1966.
1968
2013
that
therefore
2004
2007
1031,
1979
1970
1997
1975.
2008
1977.
1982,
and
1987)
2009
2009
1966,
1986
1990
the
2004
2007
1973.
1991.
2002,
1968.
Section
2004
1999.
1973
auction
1972
preferred
1974.
2006.
2001
Judgment
1993,
1981.
1996
2007,
1963.
2009
194
1990.
1944,
1981
2004
2002
2007
1997
2009
1959
2016
Criminal
1956
2006,
1968
1980.
1990
1990
Judgment
1996
1981.
2007)
2002
1994
2015
1998
were
1992
2009
dated
2017
2008
2003,
1992.
of
the
2001
2002
16.1.2001
order
1996
1989
2007
1988
2013,
2005
2010
1985)
1979
1968.
From
village
2009
proved
2015
the
2007
2009,
2004,
1985
2006
1995
1955
1993
2010
1989
out
2008
1982
1955
2000
2000.
2010
1967
1960.
1963.
1997)
was
1990.
2010
1971.
1962
2001
2003
4413
shown
2018
2015
1984
also
1995
1961,
2009
was
2008
the
1987
1972.
2009
2015
1970.
2001
1972
1986
2008
2006
1992)
found
order
1991)
1963
2010
post
2015
1990
1964
2006
2002
2008
2014,
2005
1956
1991
1997.
available
2005]
1998
to
1957,
2011,
Criminal
1987
1972.
1980
1998
any
1993
2006
2013
1993
1960
2017
of
1987
murder
1980
sentenced
1976
1998;
to
1981
[Arising
1991
2014
1976
dealing
2017
1997
1971.
1974
1994
2015
1981
2012)
2017
1991
driven
1960.
Judgment
1992
1999
2004
2013
2005
2004.
2017
1956)
1989
1986
2005)
is
Sangappa
1992
1999
1972
2011
Disciplinary
1999
1981,
Judgment
1982.
1995,
1968.
320
1972.
the
2013
1992
2010
2006)
15.07.2002.
industry;
2013
of
2006
1989,
2013
1972.
to
1996
Baran)
2005]
1998
1989
2009
December
1993
1965
1998
1985
is
1992
1989.
1979
2008
1983
had
be
2000
Magistrate
1988
1989
1975.
1974
2005
given
2014,
an
2008
manufacture,
2004
1992
2011
2011,
1992
2001
2013
1987
1995
2015
1980
1980
2010
474
Judgment
2017
2016
1973
Judgment
2007
1975
2001
1995
1953.
2009
2012
1982.
2015
2003
2008
2000
2017,
1948),
1999.
1999
1987
2010
1949
2002
1973.
1990
1983
1967
1971
(Accused
1984
2009
1994
such
1982.
1986,
1992
1983
2001
2000
2008
2010,
Out
1995
2003
v
2009
1993
1970.
of
2012
1993
IIB,
1967.
was
2008
2010)
Mali
1995
2007
1999
1975
3129
1986.
2008
by
2006
June
1974.
1999
2009
1970.
1994.
1959
1987.
1986
1970.
2016,
1995
be
2000
2000,
2009
order
1967
2003
1996
of
1988
2009
1960
1965.
2017,
1988.
1996
1955.
was
1980.
1995
12
1988
1993
2011
Judgment
2008
2011
2005
out
1986.
1990
2012
6.11.1990/Sessions
1-18/2011
2002
1960.
1980
2002
2015
2013
1983.
1960
2007
2008
2001
2006
has
1983
1988.
1985
shall
been
the
(Arising
2002
1982
the
2016
Annapurna
1972.
2008
1984
Trial
1952
been
1993.
1976
be
on
1989
2013,
1972.
1992.
2001
1998.
2003
2003
2006)
2012
1993
1965
Judgment
2007
report
2002
1999,
2002
2003
1975.
Town
was
1990
August
Judgment
1956.
1981
interviewed
1959
1999,
1973
facts
of
1976.
2008
1971.
of
to
3
2001.
1.4.615
2010
be
2008
or
is
1967.
1991
94
2002
1972)
2016
2001
1982.
1996
2002
1956.
1989
1995
1991
2013
1966.
1985
additionally
1974.
1985,
2002
of
2008,
1969.
1983.
1988
2011
1961
1975
1988
1985.
1972.
1978.
2006
was
2005
1964.
2010
the
2007
in
2003
1960.
2017
2001
2004
2009
2012
2008
2010)
to
Road
1996
1978
1956.
1978
2012
1987
2000
Cr.A.
1996
1994
2001
1990.
states
No.
1972
2004]
2009
2013
described
1986
1961,
1977.
2000
of
2009
dismissed
1972.
Dakshinamoorthy)
1980
1973
1981
2015
the
examined
1995
1982
1972.
2001
the
1984
2007
then
180
injuries
Crl.
1978.
2011
pulled
Dhana
1959
be
2003
1957.
1976.
was
2001
(Arising
1993
Palace,
1957.
1958
2014
1971.
1960
1999
from
1968.
1980.
1967.
1988
2007
19.7.2006.
2008
1984
1980
2009
2014
1961.
2012
1975.
offered
2003
2014
1962,
1995,
1998
1982,
Section
1992
2003
1981
1960
1967.
Cr.A.
2014
2009
2003
2007
The
2001
2001
2012
2007
2006)
2007
2007
2005
1971
OF
1993,
2005)
1981
1993.
2015
2007
1971.
in
Art.
1998
1981
1984.From
2007.
2009)
was
1976.
2004
serving
2014
2009
1993.
1998
1998
1967.
2004
Criminal
1984.
1958
2009
2003
2013
1998
1999
order
to
his
1990
1997
1990
1997
1980
2001.
4
2008
2016
2003
him
1996
2006
1989
1984
1980
1979
2001.
2009
2010
2003
2017
2008
1974.
2016
2000
1971
1953.
1998
notice
1995
1974.
2012
1986.
1974
1961
1973
1973.
its
2014
2001.
2006
2008)
one
2002
shall
2007
1996.
2002
1989
1957.
the
2018
2013
1957
1983
2008
1953.
2006
2009
2000
be
2008
2009
creating
2010
2008,
there
2001
409
or
2000
1970
1995
1996
1982
Criminal
1963
2009
2006
1976.
2009
1991
High
1994
1995
2011
2002
2015,
1981
Sections
1984
1986
2005
2002
2014
1992
1993
1994
1984
2016
1965
crushing
March
1999
1995
2012,
1975.
No.
1990)
his
2007.
1982
1996
2002)
2009
2008
1966.
2009
1975.
1997
the
dated
February
1974.
1960
2000
1993
1954.
2006)
and
1963.Appeal
2017
1988
also
2001
1961
1982,
2015
1961
2018
1993.
1967
1981
2001
dated
2009
1996
1974.
1982
the
1967.
2007,
1991
2009)
2009
2012,
his
2008
1996
1993.
from
2009
1980
1983
2008)
2012
1968
2010
2014
2011
1975
2010
1982,
Peddampuram
2006
2005
which
1958
1959
the
1977
24.11.1988
2014
22.5.2011
1989
1983.
1952.Appeal
1968,
2013
1989
2000.
enter
M/s
1996
1974.
2010
2002
2009
1981
1969.
1966
1975.
1971
1989
2002
the
The
1991
1989
lord
reads
2000
2003
2012,
2011
1989.
1957
No.
1952
1985
1960
2003
2003
2004
appointment
2012
1960
2014
2003
injury
version
accused
1961.
2008
to
1972.
1969.
2005
(Q)
1995
1965
1979
1993
2017
1955
1962
2001
ever
1986
a
2003
1982,
been
after
2003)
2016
2018
Both
1957.
1982
1963
2015
fast
123
1995
1983.
IA
2002
by
the
2004]
1990.
2014
2007
2007
1977
2004
2016
2003
2009
2008
1959.
1958
1954.
1976.
1981
1981.
Chandra
2001,
is
appellant
to
Judgment
1993.
discrimination
2012)
1979.
2015
2010
1989
2003
a
1999
preferred
A-2
2015
2008
2013
claim
1996
2009
2012
2003.
Allowed
1996,
the
898-905/75.
Judgment
2007)
1989
2005
1983
1991
Order
inguest
1964
2008
2006)
1965
2011)
2011
noticed
3544/97,
Ram
1990.
2009
1988
1967
1990
Order
1995
2006)
15th
2011
2002
has
2006
2013
2000
2004
F
2008
1995
2011
2002
1981.
April
1968.
(Arising
2009
expressed
1984.
1962.
1996
1986
1954
2017
2004
1997
were
1983
restored
2001
2012,
1982
1979
2001
Plot
2010
5
2002
1967.
2017
2000
2001
to
1992.
1997
father)
by
2004)
2018,
1318
1
1965
1999
1979
No.
1976
against
2009
2003
2007
1993
1961
is
1969
2012
1995,
2007
1998
2005
2002
examined
2015
2002
2007
ligature
and
2009
1972.
2009
Schedule
1966
1980,
the
his
2001
1978.
2004
law
2009
miscarriage
1993,
has
1987
put
2002
2008
2015
the
made
2008
thus
and
2002
2008
1982
1976
1998
2013
2005
1995
the
the
1977.
1967
2006]
1981
2000
2012,
the
1998
1991
2007
1979.
1982
Judgment
1997
2008
1996
No.
2002
could
third
to
1971
under
1999
that
2005
2013
2005
2015,
1974.
1984
1992
2017
a
1980.
1998
1980
were
1969
fast
1969
15527/2010
by
1972.
1999
1954
2004
2005
2002
1968
was
1996
1982.
2012,
1955.
1970.
the
1998
2006)
1963
1992
1992
2008
1975
1973
1995
1971.
Judgment
1978.
2010),
1955
1968.
2010
1988
Judgment
1999
1959
1995
1978
a
1973.
1980
1969
forthcoming
SLP
1A2
2000
1996.
1970.
2007
been
1983)
2006
Act-15-48-Order-98
1997
2009[Arising
2001
the
2012
1964
2011
1984
either
2014
him
1987
2009
2006)
1979
2000
1984
2003
1959
2000
2010
2010
2001
2004
1968
2006
1971
2001
2001
2008
2014
dated
2004
2013
2012
1970
2004]
2013
1987
2018
1987
1978
be
2008
2004
2007)
2018
2017,
1980
2012
2005
1984
1956.
can
2003)
rules
2009
whereupon
1967
1989
1998
2001
1954
2008
2008
1968.
1994
the
1999
2008
2017
1970
found
Allowed
1970.
receipt
the
2015
3rd
1975.
307
2002
created
concerned,
the
2008
1997
1953
2011
1957
2008
2008
1995.
2015
1995
1999
1996)
1992
1980.
1999
1997
in
1939.
1968.
1992
1960.
2010
1985
1982
1981
1967.
The
her
1994
2014
1992
found
1969.
2018
2009
1984
1979
2007
1985.
2003
2009
1966
Crl.A.No.408/2005
2003
found
1999
Order
towards
1974.
pendency
Gopal
1999/2003
1997
out
2007
1960
1983
2009
forthcoming
1999
During
2008
2009
interest
2007
1988.
1956
2006
2007)
2008
1979.
2006;
2001
1986
1959.
1990.
2007
2009
1996
out
1989.
1984,
2008
1981
his
2008
2016
1979
1984.
2002
1970.
1983
2014
1969
of
fast
2012)
1980
1970.
dated
2008
2007
1972.
Judgment
the
2014
2010
1974.
2003
of
1980
1966
2003]
2005
1969
2005
2012)
2000
was
put
respondents
1976.
2013
2003
2007
as
2016
2007
(Arising
2007
1992
2001
2009
2001
1994,
2010.
2011
1967.
1977.
1994
2002.
2005
2006
2016
2008
can
1979.
1981
1971
complaint
1954.
2003]
an
hold
1967
1953.
2009,
1964
1998
1985
1998.
out
1999
2000
1991
2001
1994,
1959.
2008
be
the
XXIII-PWD-90
2015
1991
was
2004)
1981
2008
24-1-1987
1996
1992
1999
1998
1958)
2004]
3
2012
2006
1989
2013
3520-3524/2002
2010
304
1986
2009
1980
2016
2010,
1974,
1996,
the
2011
1976
1971
(W)
1998
2011
in
1996.
2004
@
1975
2008
C)
with
1991
2006
noticed
1991
12.11.1985
a
1992
1972.
came
1989
2008
1989.
1972.
2011[Arising
the
2008
1972.
1996
1996
of
1972.
1974.
2011)
2017,
1997
2007
1964.
2010
1979
2014
1987
the
1999
interpretation
1974
about
is
2015
2005
the
2001
1971
1984,
1994
2015
1963)hereinafter
2010
to
2008
2007
1980.
2012
2014
1983
can
2002
1959.
2001
had
1986
2009
2000
1993:
2005
1997
1987
Respondent
2003
been
2014
2005
2008
1999
2003
1957.
2005)
Appeal
2009(Arising
The
2004,
2000
1980
2014
1981
1995
1978
1956
2010,
the
Order
2008
2008
fast
1992
03.03.2001
1989.
2002
WITH
2010,
2003)
ever
The
2001
1996
1969.
2006)
1986
1981.
1985
1983
the
2016
1979
2008
2008
1991
1996
1959.
2008
was
of
2005
2003,With
than
the
1969.
and
CBI
2013
2008
2007
2014
1962
1976.
1960
1954.
Judgment
1952,
The
2002
committed
2003
2008)
2010
An
1974
1960
1971.
2007
2009.
1990
this."
1958.
1987
1986.
1999
2002]
2009
1980.
2008
12.11.1979
2010,
2008]
460
1973
1977.
1997
1996
has
1988
out
1988
The
are
1979
1972
2004)
1979
Judgment
2017
1895
2009
1981
2006
also
2006
1984.
2008
(Arising
1955)
allowed
1959
2003
1993
1997
1996
and
1957
2004
2004.
1979
does
2007]
2013
2008
a
(hereinafter
2000]
2010
1968
1986.
1998
1971
1985
2008)
sell
1986
1973.
Judgment
09.08.2010,
dated
1981.
No.
2009
2008
1997,
1999
was
1989.
1986
2003
2002
2005
1966.
2004
2008
1994
1990
1976
1952,
2015
1993
1997
1989
2000
OF
deposed
information
1960
1960
1968.
2009
are
2003
2008
Book
2006)
been
possible
1970
2001
(C)
1991
1955.
1972
1996
1972.
1981
1995
the
2009
allowed
1980
dismissed
2001
1999.
2017
2009,
1997
1989
2005)
2011
1969
1975
1994
2004
2009
1983
1984,
1981
referred
2006.
1970.
1998
1985
1978
Thereafter
on
Judgment
of
2016
1982.
detained
2016
1981
1987
1985
1961.
1990
1972.
1970.
the
1980),
1984
has
(Arising
1993
2004
receipt
1979
2002,
x
2001
2000
1988
2002
1972.
2008
1996
1966
forthcoming
was
1959
and
2000).With
1998
2006)
2009
2004]
is
1971.
2002
authorized
1953
dated
1971.
Appeal
1996
Judgment
2006)
down
effected
2000
2006)
injured
2010
Sekhar
1980
a
1998
fast
2007
is
2009
1958
the
1992.
1992
1992.
appellants
2001
1994
1987
1967.
1985
Shri
2006,
2007
1969
2009
2011
driven
1996
1998
disputed
Satish
Bhenkarbhai
Judgment
2015
2007
and
that
1981.
1982
1989.
1993
with
2006)
1996
be
1962.
2001
1972.
1977.
1976.
(Arising
been
2008
of
2009
2011
1992
1999,
1969.
1978
1979
2009,
2002
1995
2005]
cast
1999
1980
2013
2004
2013
2011.
1973
2001
2007
2005
1978
1977.
2004
2009
1981
dated
be
2008
cannot
2012,
2008
1996
1984,
1990
2001
2012,
2017
1998
1989
1972.
2005
2001
1958.
2010
562
2005.
2008
Order
1975
to
1990
1993
1966
2015
1985.
1996,
2008
evidence
2016
2007
1985
2008
575
2010
The
1984
1983
2014
July
1996
2007
1999
1962,
1992
2016)
Judgment
1996
1989.
2005).
1973.
1991
2006)
1978.
1998
2005
2014(From
been
for
1999
1971
1994
2007)
1999
2000
2016
2009
2014
1989
1995
1998
1999
1965,
1982
1971
made
1978,
Koil
Section
an
1999)
2004]
1962
2014
2007
1992
1983
2001
1979)
1986.From
expressed
1965
Bajaj
2012
2017]
2013,
2015
1992
its
2013
1995
2008
2010
98
1969
2012
of
2007]
1999
also
1996
2012
1977.
Razwana
by
2008
a
1967.
2008
High
2010)
1999
registered.
caused
1976
fast
1996,
1991
1966,
2014
2001
1980
2008
1991
1963.
1981
2003
2017
Judgment
1999
2017
1975.
1979
1954
the
1968.
2001
2010
Development
1975
2014
2004
Civil
959
1970.
1974
Schedule-11
2008
1/69/PMI180
1987
(Arising
order
1993.
is
The
2006
1970
1995
1984.
2007
1969.
2008,
1956.
2015
1980
2012
in
2003
1987.
607
2008
be
1980
1998
2009
given
2004
of
2008
1991
having
1959
Shamanaik)
1999
1978
1995
1970,
2005
1970.
dated
1968.
of
2005
2009
1988
1995
1986
1999
2004
1968.
1997
1974
1990
2017
per
2001
1988
1994
2015,
1988.
been
1959
1980
1969.
Court
1992
Order
1967.
2004]
can
1985
1966
1997
1994
2000
2014
2013
1978
approach
1985
1979
2008
DB
1984
2006
1985
1982
1986
2000.
2011,
1958.Petition
was
which
of
2004
1990
2013
1979
2006]
1989
Judgment
2004)
1996
1962.
falsely
2003,
1982
2007
1992
were
1994
1956.Appeal
1981.
1990
any
1992
1996
found.
2008
2007
8501
2015
1957.
1978
be
1981
2007)
1991
1970.
2001
1971.
1963
1981.
to
1955.
1966.
1961
2006
by
Order
2010
2001
1998
1996]
1978.
1978
from
however,
Dismissed
2012
2013,
1981
1978.
going
through
2016
1981
1999
1979
2007
1965
2003
2004,
1990
identified
2000.
1989
1990
2011]
1995
1961
1978.
been
2008]
2008
2008
1996
of
2016,

In [54]:
df['End']=f
print(df)

                                                   Text              Start  \
0     Masud Khan v State Of Uttar Pradesh Supreme Co...  26 September 1973
1     Prabhakaran Nair, Etc. v State Of Tamil Nadu A...   3 September 1987
2     Hiten P. Dalal v Bratindranath Banerjee Suprem...       11 July 2001
3     Ashok Kumar and Others v State of Tamil Nadu S...         5 May 2006
4     Ashok Dhingra v N.C.T. of Delhi Supreme Court ...       3 March 2000
...                                                 ...                ...
2909  Rajendra Singh v State of Uttaranchal Supreme ...      11 April 2013
2910  Food Corporation Of India & Anr v Seil Ltd. & ...    11 January 2008
2911  State of Kerala v Sasi Supreme Court of India ...    31 October 1996
2912  Columbia Sportswear Company v Director Of Inco...       30 July 2012
2913  Bharat Gurjar and others v State of Rajasthan ...       9 March 2017

        End
0      1973
1      1986
2       why
3     2004)
4     2000.
...     ...
2909   2008
2910      0
2911   1996
2912     of
2913  2016,

[2914 rows x 3 columns]

In [55]:
len(f)

2914

In [56]:
df

,Text,Start,End
0,Masud Khan v State Of Uttar Pradesh Supreme Co...,26 September 1973,1973
1,"Prabhakaran Nair, Etc. v State Of Tamil Nadu A...",3 September 1987,1986
2,Hiten P. Dalal v Bratindranath Banerjee Suprem...,11 July 2001,why
3,Ashok Kumar and Others v State of Tamil Nadu S...,5 May 2006,2004)
4,Ashok Dhingra v N.C.T. of Delhi Supreme Court ...,3 March 2000,2000.
...,...,...,...
2909,Rajendra Singh v State of Uttaranchal Supreme ...,11 April 2013,2008
2910,Food Corporation Of India & Anr v Seil Ltd. & ...,11 January 2008,0
2911,State of Kerala v Sasi Supreme Court of India ...,31 October 1996,1996
2912,Columbia Sportswear Company v Director Of Inco...,30 July 2012,of
2913,Bharat Gurjar and others v State of Rajasthan ...,9 March 2017,"2016,"

In [57]:
l=[]
for i in zip(jud,f):
    l.append(i)
print(l)

[('26 September 1973', '1973'), ('3 September 1987', '1986'), ('11 July 2001', 'why'), ('5 May 2006', '2004)'), ('3 March 2000', '2000.'), ('11 September 1962', '1962'), ('7 September 2010', '2010'), ('17 January 1968', '1967.'), ('25 November 1959', '0'), ('6 August 1982', '1981'), ('11 August 2003', '&'), ('25 January 2000', '1995.'), ('7 October 1994', '1993'), ('10 August 1999', '1977'), ('4 May 2009', '2003'), ('14 January 1992', '1981'), ('30 January 2012', 'make'), ('23 November 2006', 'therefore,'), ('30 August 2007', '0'), ('19 April 2004', '0'), ('24 April 2002', '0'), ('22 August 1969', '1967.'), ('3 March 1971', '1968.'), ('29 January 1975', '1972'), ('6 December 1960', '1959,'), ('10 January 2005', '2005'), ('8 July 2010', '8th'), ('19 July 2011', '1997'), ('23 February 1970', '1967'), ('30 October 2001', 'accused'), ('1 April 1998', '0'), ('16 August 2010', 'Bhardwaj'), ('12 August 2014', '2005.'), ('23 February 1971', '1969'), ('3 March 2005', '2004'), ('4 November 1997', '1997'), ('31 October 2003', '0'), ('12 September 1978', '1972'), ('17 December 2003', 'the'), ('22 March 2013', '2002,'), ('11 August 2005', 'Kant'), ('30 October 1969', '1966'), ('13 February 1980', '305/78.'), ('13 December 2012', '2010'), ('2 January 2017', '1998'), ('19 February 2007', '2006)'), ('26 September 2003', '1996'), ('24 April 2009', '2009'), ('29 November 1991', '1990'), ('5 October 2005', '2003)'), ('11 May 2005', '0'), ('3 October 1979', '1979'), ('9 May 2008', '2002'), ('31 July 2003', '2002'), ('2 May 2017', 'of'), ('31 March 2009', '2004'), ('14 March 1972', 'C.A.'), ('12 April 2004', 'one'), ('14 November 2011', '2004'), ('12 May 2011', '2011(Arising'), ('6 November 2006', 'the'), ('2 July 2014', '2004'), ('24 January 2002', '2001'), ('7 October 1969', '1968'), ('5 November 1971', '1968,'), ('17 September 2002', '2000'), ('29 March 2000', '2000'), ('30 July 1992', '1992'), ('10 December 1999', '0'), ('8 May 2009', '2009'), ('21 August 1995', '0'), ('16 January 1987', 'Minister'), ('28 July 1999', '1998'), ('14 September 2006', '0'), ('26 August 2003', '2002'), ('7 May 1996', '1996)'), ('8 February 1972', 'to'), ('14 September 1976', '1971'), ('26 April 1974', 'Chief'), ('5 March 1998', '1991'), ('8 March 1989', '1978'), ('16 December 2011', '2010'), ('19 April 1961', '1960'), ('27 February 2009', '2008.'), ('2 May 1977', '1971'), ('21 February 1983', '1980'), ('7 January 1997', '1988'), ('3 September 1998', '1996'), ('24 January 2002', '2002'), ('13 March 1990', '1977'), ('18 September 1987', '1987'), ('4 November 1982', '1982'), ('22 November 2004', 'been'), ('10 February 2011', '2003'), ('15 October 2003', 'Khasra'), ('6 May 2009', '2009[Arising'), ('4 March 2014', '2014'), ('21 August 1990', '1972'), ('30 November 1978', '1974,'), ('18 January 1994', 'Order'), ('15 December 2014', '2012'), ('7 August 1990', 'for'), ('29 September 2008', '2008'), ('4 July 2016', '2011'), ('27 March 2014', '2014'), ('13 February 1976', '1971.'), ('29 September 1967', '1966'), ('28 February 1974', '1973'), ('8 August 2008', '1980'), ('27 January 2000', '1998'), ('9 March 2010', '2010'), ('12 April 1979', '1974.'), ('9 July 1996', '1995'), ('6 November 1990', '1974'), ('25 April 2005', '0'), ('27 April 2004', '1998'), ('2 May 2008', '2006'), ('29 January 2002', '0'), ('25 November 2003', '0'), ('14 February 1991', '1977'), ('10 February 2004', '0'), ('28 November 2014', '2014'), ('27 January 1975', '1974,'), ('27 November 1996', '1996'), ('29 August 1989', '1987'), ('20 January 2011', '0'), ('18 July 1972', '1971.'), ('5 February 2014', '2004'), ('12 April 1999', '1999'), ('12 November 2014', '2014'), ('9 October 1969', '1967'), ('20 August 1964', '1963.'), ('7 February 1958', '1957.'), ('3 April 1967', '1966,'), ('7 March 1962', '1955'), ('26 October 1998', '1998'), ('26 September 2008', '0'), ('13 December 2007', '0'), ('18 September 2003', '1990'), ('9 February 1990', '1990'), ('10 March 1983', 'applications'), ('18 July 2006', '0'), ('1 July 2015', '2015'), ('28 November 2006', '0'), ('6 September 1974', '1973.'), ('13 August 1998', '1998'), ('28 March 2008', '2008'), ('24 July 2001', 'sanction'), ('5 January 1998', 'Smt.'), ('6 March 1992', '1979.'), ('9 January 1991', '1988'), ('7 May 2010', '2010'), ('10 May 2012', 'held'), ('16 January 1969', 'made'), ('22 March 2012', '2006'), ('30 July 2010', '2010)'), ('6 April 1989', '1979'), ('20 December 1991', '1991'), ('20 February 2017', '2013'), ('1 August 2002', 'Ram'), ('11 March 2003', '1999.'), ('4 February 2013', '2006,'), ('6 May 1996', 'appellant'), ('20 March 2009', 'allowed'), ('7 October 2009', '2009'), ('12 April 2016', '2016'), ('6 May 2009', '2006'), ('21 February 1978', '1975'), ('19 November 1963', '1963.'), ('1 September 2014', '0'), ('26 April 2013', '2009'), ('3 March 2008', '2008'), ('6 November 1990', '1979'), ('17 April 2009', '2001'), ('8 October 2004', '1999'), ('14 July 1993', '1988)'), ('2 September 2005', '2004'), ('2 February 2017', '2011'), ('12 February 1987', 'State'), ('25 August 1988', '1987.'), ('8 May 2014', '2008'), ('15 September 2016', 'the'), ('3 October 1979', '1979'), ('15 January 2015', 'Judgment'), ('4 January 2008', 'inflicted'), ('31 January 1979', '1969.'), ('31 August 1989', '1981'), ('17 November 2003', 'was'), ('15 October 1992', '1982'), ('25 February 2014', '(Arising'), ('31 July 1996', '1995'), ('26 March 2009', '2004'), ('7 November 2006', '2005'), ('22 July 2003', 'offence'), ('2 August 2005', '2005'), ('18 July 2016', '2014,'), ('12 March 1992', '1992'), ('15 January 1971', '1966.'), ('3 May 1989', '1989'), ('11 January 1991', '1991'), ('9 March 1981', '1980.'), ('5 April 2002', '0'), ('28 November 2008', '2008'), ('29 May 2009', '2004'), ('17 December 1999', '0'), ('3 July 2013', '2007'), ('6 October 2009', '0'), ('29 September 1994', '1987'), ('15 January 2002', '2002'), ('15 September 2010', '2004'), ('11 September 2001', '0'), ('25 March 2014', '2008'), ('10 May 1985', 'was'), ('17 June 2009', '1997'), ('27 February 2002', '1963'), ('9 February 2009', '2009'), ('18 November 2004', '0'), ('4 December 1992', '1985'), ('27 August 2003', '0'), ('31 July 2009', 'was'), ('3 July 2006', 'receipt'), ('13 November 1980', '1977.'), ('6 January 1999', '1983'), ('2 May 1989', '1978'), ('13 March 1953', '0'), ('13 March 1975', '1971.'), ('1 February 2010', 'the'), ('16 September 2014', '2014'), ('14 March 2008', '2006)'), ('18 April 2000', '1998'), ('10 January 1957', 'the'), ('15 September 2010', '2010)'), ('29 August 2002', '2000'), ('22 October 1991', '1991'), ('12 May 1995', '0'), ('25 August 1988', '75'), ('25 September 2001', '1999,'), ('12 December 2002', '1996'), ('2 February 2007', 'deputation'), ('28 November 2014', '2014'), ('29 August 2000', '1991'), ('15 January 2015', '2015'), ('3 November 1992', '1982'), ('19 October 2001', 'therefore,'), ('23 February 1993', '1979.'), ('3 February 1993', '1990'), ('27 August 2002', 'to'), ('14 September 1978', '1977).'), ('24 January 2013', '2009)'), ('18 November 2003', 'BACKGROUND;'), ('5 March 1980', 'dated'), ('19 November 2010', '1988.'), ('4 February 2004', '0'), ('5 May 1954', '1954.'), ('8 August 1979', '1973.'), ('5 November 2008', '2007'), ('22 August 1968', '0'), ('16 December 2010', '2005'), ('9 July 1991', '1987'), ('16 November 2006', 'It'), ('22 February 1974', '1973'), ('2 July 2014', '2006'), ('5 May 1989', '1984.'), ('31 October 1972', '1972.'), ('1 March 1971', '1968'), ('20 August 2007', '2005'), ('26 November 2010', '0'), ('21 August 1997', '1993,'), ('8 May 1998', '1990'), ('20 October 2008', '2008'), ('7 November 2008', '17th'), ('23 February 2018', '2018'), ('10 August 1994', '1990'), ('5 May 2004', '0'), ('25 August 2009', '2005'), ('14 December 1971', '(Transport'), ('31 October 2002', '1999'), ('25 July 2001', '2001'), ('22 July 1998', '1989'), ('9 September 1996', '1981'), ('5 May 2008', '1989,'), ('15 January 1999', '38/98'), ('27 March 2009', '0'), ('24 January 1983', '1982'), ('16 August 2012', '2009'), ('21 March 1996', '1995,'), ('14 May 1999', '1991'), ('3 January 2017', 'Criminal'), ('9 December 2014', '2014'), ('22 August 1984', '1981,'), ('11 May 1988', '368'), ('16 February 1983', '1983.'), ('20 October 2005', 'The'), ('21 April 2009', 'is'), ('29 July 1998', 'Order'), ('11 July 1996', '1989,'), ('31 January 1968', '1966.'), ('12 March 1969', '1968'), ('12 March 2014', '2013'), ('29 September 2006', 'that'), ('3 February 1964', 'therefore'), ('16 November 2006', '2004'), ('12 October 2012', '2007'), ('27 January 1965', '1031,'), ('5 May 1993', '1979'), ('9 January 1973', '1970'), ('15 July 2003', '1997'), ('9 April 1980', '1975.'), ('14 September 2012', '2008'), ('9 May 1980', '1977.'), ('16 October 2008', '0'), ('24 February 1988', '1982,'), ('12 July 1996', 'and'), ('25 November 1997', '1987)'), ('28 July 2009', '2009'), ('6 October 2016', '2009'), ('22 September 1967', '1966,'), ('24 November 2003', '0'), ('9 February 1988', '1986'), ('21 August 2002', '0'), ('12 February 2008', '0'), ('27 August 1991', '1990'), ('8 November 2000', 'the'), ('14 December 2004', '2004'), ('8 January 2007', '2007'), ('6 November 1979', '1973.'), ('31 October 1991', '1991.'), ('27 September 2004', '2002,'), ('29 January 1976', '1968.'), ('31 October 2001', '0'), ('21 October 2008', '0'), ('15 October 2008', '0'), ('20 January 2003', 'Section'), ('3 September 2004', '2004'), ('26 April 1999', '1999.'), ('18 January 1979', '1973'), ('24 August 2006', 'auction'), ('5 December 1975', '1972'), ('10 August 1978', 'preferred'), ('13 August 1974', '1974.'), ('13 February 2001', '0'), ('14 August 2001', '0'), ('12 January 2010', '2006.'), ('13 January 2004', '2001'), ('1 May 2001', 'Judgment'), ('8 December 1999', '1993,'), ('28 July 1981', '1981.'), ('20 September 1996', '1996'), ('10 April 2017', '2007,'), ('26 July 2010', '0'), ('3 March 1965', '1963.'), ('23 August 2004', '0'), ('18 October 2012', '2009'), ('5 October 1972', '194'), ('7 November 2008', '1990.'), ('30 July 2014', '0'), ('26 November 1954', '1944,'), ('12 August 1981', '1981'), ('20 January 2006', '2004'), ('29 April 2004', '0'), ('28 November 2008', '2002'), ('12 January 2009', '0'), ('11 March 2015', '2007'), ('5 February 2004', '1997'), ('16 January 2009', '2009'), ('7 April 1960', '1959'), ('22 April 2016', '2016'), ('15 March 2004', 'Criminal'), ('25 January 1961', '1956'), ('6 December 2006', '2006,'), ('30 March 1971', '1968'), ('3 September 1980', '1980.'), ('2 August 2000', '1990'), ('5 November 1993', '1990'), ('15 February 2007', 'Judgment'), ('17 October 2013', '1996'), ('8 March 1988', '1981.'), ('24 March 2009', '2007)'), ('12 November 2002', '2002'), ('12 May 1999', '1994'), ('11 May 2015', '2015'), ('6 February 1998', '1998'), ('6 May 2010', 'were'), ('11 August 1992', '1992'), ('26 April 2013', '2009'), ('29 January 1964', 'dated'), ('5 May 2017', '2017'), ('14 March 2008', '2008'), ('18 September 2006', '2003,'), ('28 March 2000', '1992.'), ('15 November 1989', 'of'), ('11 September 1979', 'the'), ('9 July 2008', '2001'), ('2 September 2003', '2002'), ('1 November 2002', '16.1.2001'), ('30 October 1981', 'order'), ('19 March 2002', '1996'), ('23 August 1996', '1989'), ('31 January 2003', '0'), ('20 August 2008', '0'), ('3 July 2013', '2007'), ('10 May 1988', '1988'), ('23 May 2014', '2013,'), ('28 April 2006', '2005'), ('25 August 2011', '2010'), ('11 April 1988', '1985)'), ('3 May 2007', '0'), ('5 February 1988', '1979'), ('4 April 1977', '1968.'), ('22 April 1992', 'From'), ('10 October 2007', 'village'), ('15 May 2009', '2009'), ('9 June 2011', 'proved'), ('20 January 2015', '2015'), ('2 September 2014', 'the'), ('3 March 2016', '2007'), ('16 October 2012', '2009,'), ('5 March 2008', '2004,'), ('8 July 1997', '1985'), ('1 September 2010', '2006'), ('5 December 1995', '1995'), ('16 May 1957', '1955'), ('2 February 1993', '1993'), ('3 March 2005', '0'), ('4 December 2006', '0'), ('13 August 2010', '2010'), ('18 December 1992', '1989'), ('16 April 2015', 'out'), ('13 October 2008', '2008'), ('12 February 1996', '1982'), ('5 April 1956', '1955'), ('13 April 2005', '2000'), ('9 September 2002', '2000.'), ('10 August 2010', '2010'), ('23 August 1971', '1967'), ('12 December 1962', '1960.'), ('22 October 1963', '1963.'), ('27 April 1998', '1997)'), ('24 July 2009', 'was'), ('10 October 1990', '1990.'), ('8 February 2010', '2010'), ('23 March 1976', '1971.'), ('18 March 1964', '1962'), ('3 April 2001', '2001'), ('14 February 2008', '2003'), ('6 April 1986', '4413'), ('11 January 2008', 'shown'), ('15 February 2018', '2018'), ('17 February 2003', '0'), ('6 April 2004', '0'), ('1 December 2015', '2015'), ('27 February 2003', '1984'), ('8 January 1994', 'also'), ('30 August 1978', '0'), ('26 February 2007', '1995'), ('8 August 1962', '1961,'), ('11 November 2009', '2009'), ('6 December 2006', 'was'), ('14 May 2010', '2008'), ('11 March 2011', 'the'), ('20 November 1987', '1987'), ('18 September 1973', '1972.'), ('31 March 2009', '2009'), ('13 March 2015', '2015'), ('20 August 1981', '1970.'), ('19 November 2008', '2001'), ('16 January 1979', '1972'), ('11 August 1987', '1986'), ('24 February 2014', '2008'), ('2 March 2017', '2006'), ('5 February 2004', '1992)'), ('7 July 2011', 'found'), ('29 October 2001', 'order'), ('13 October 1992', '1991)'), ('4 November 1964', '1963'), ('6 July 2010', '2010'), ('3 August 2012', 'post'), ('25 August 2015', '2015'), ('21 June 2007', '0'), ('28 August 1992', '1990'), ('16 September 1965', '1964'), ('13 May 2009', '2006'), ('11 September 2003', '2002'), ('17 October 2008', '2008'), ('22 January 2015', '2014,'), ('9 January 2008', '2005'), ('12 February 1957', '1956'), ('23 October 1992', '1991'), ('11 January 2008', '1997.'), ('25 March 2009', 'available'), ('18 December 2008', '2005]'), ('28 November 2003', '0'), ('13 August 1998', '1998'), ('13 December 2006', 'to'), ('26 November 1959', '1957,'), ('9 October 2015', '2011,'), ('1 September 2008', 'Criminal'), ('30 March 1987', '1987'), ('6 November 1990', '1972.'), ('7 February 2007', '0'), ('6 September 1995', '1980'), ('14 December 1998', '1998'), ('8 November 2005', 'any'), ('7 April 1993', '1993'), ('15 July 2008', '2006'), ('15 July 2013', '2013'), ('17 December 1996', '1993'), ('4 April 1962', '1960'), ('6 February 2017', '2017'), ('2 May 1990', 'of'), ('14 July 1994', '1987'), ('13 August 2002', '0'), ('1 November 1955', 'murder'), ('3 August 1995', '1980'), ('13 January 2009', 'sentenced'), ('20 February 1981', '1976'), ('3 April 2007', '0'), ('14 August 2001', '1998;'), ('7 March 2011', 'to'), ('14 January 1992', '1981'), ('27 April 2007', '[Arising'), ('26 August 1993', '1991'), ('8 September 2017', '2014'), ('31 March 1981', '1976'), ('28 July 1966', 'dealing'), ('24 August 2017', '2017'), ('21 January 2000', '1997'), ('24 January 1972', '1971.'), ('16 April 1975', '1974'), ('9 November 2000', '1994'), ('28 July 2015', '2015'), ('25 January 1995', '1981'), ('9 May 2013', '2012)'), ('24 April 2017', '2017'), ('5 March 1998', '1991'), ('8 December 2004', 'driven'), ('10 October 1969', '1960.'), ('6 April 1962', 'Judgment'), ('5 February 1997', '1992'), ('22 September 1999', '1999'), ('31 March 2009', '2004'), ('4 October 2013', '2013'), ('7 September 2007', '2005'), ('26 February 2008', '2004.'), ('31 January 2017', '2017'), ('8 April 1965', '1956)'), ('9 November 1989', '1989'), ('2 September 1997', '1986'), ('6 September 2005', '2005)'), ('6 January 2006', 'is'), ('12 November 2002', 'Sangappa'), ('10 February 1993', '1992'), ('12 December 2000', '1999'), ('16 September 2003', '0'), ('26 March 1980', '1972'), ('15 October 2015', '2011'), ('23 January 2003', 'Disciplinary'), ('12 March 1999', '1999'), ('2 December 2008', '1981,'), ('24 August 1976', 'Judgment'), ('26 October 1987', '1982.'), ('26 February 1998', '1995,'), ('23 April 1971', '1968.'), ('7 March 1972', '320'), ('20 April 1977', '1972.'), ('9 May 2000', 'the'), ('9 May 2014', '2013'), ('15 January 2008', '1992'), ('16 September 2014', '2010'), ('15 September 2006', '2006)'), ('8 May 2012', '15.07.2002.'), ('21 February 1978', 'industry;'), ('9 February 2017', '2013'), ('7 January 2003', 'of'), ('26 October 2010', '2006'), ('4 April 1989', '1989,'), ('19 February 2013', '2013'), ('28 February 1979', '1972.'), ('24 July 2008', 'to'), ('15 May 2013', '1996'), ('22 November 2012', 'Baran)'), ('20 February 2007', '2005]'), ('13 May 2005', '1998'), ('1 October 1991', '1989'), ('13 April 2004', '0'), ('11 October 2011', '2009'), ('9 November 1990', 'December'), ('29 October 2002', '1993'), ('23 July 1968', '1965'), ('29 March 2005', '1998'), ('30 March 1993', '1985'), ('17 September 2004', 'is'), ('18 December 1992', '1992'), ('24 November 2004', '1989.'), ('4 October 1991', '1979'), ('22 July 2010', '2008'), ('18 January 1994', '1983'), ('1 November 2006', 'had'), ('15 October 2008', 'be'), ('27 September 2010', '2000'), ('8 November 1996', '0'), ('29 September 1999', 'Magistrate'), ('24 November 2004', '1988'), ('9 May 1996', '1989'), ('18 March 1976', '1975.'), ('19 August 1976', '1974'), ('2 November 2007', '2005'), ('21 August 2003', 'given'), ('23 May 2014', '2014,'), ('13 October 2003', 'an'), ('4 September 2002', '0'), ('8 July 2010', '2008'), ('14 December 2012', 'manufacture,'), ('22 April 2008', '2004'), ('21 January 1998', '1992'), ('4 July 2011', '2011'), ('3 August 2017', '2011,'), ('15 April 1998', '1992'), ('7 November 2008', '2001'), ('24 October 2013', '2013'), ('20 February 1987', '1987'), ('13 May 1998', '1995'), ('17 March 2015', '2015'), ('15 April 1982', '1980'), ('11 November 1980', '1980'), ('1 November 1996', '0'), ('9 February 2016', '2010'), ('4 December 2003', '0'), ('5 September 1972', '474'), ('18 March 2004', 'Judgment'), ('23 February 2017', '2017'), ('9 August 2016', '2016'), ('20 February 1987', '1973'), ('12 May 2006', 'Judgment'), ('17 February 2010', '2007'), ('23 August 1990', '1975'), ('20 July 2004', '2001'), ('15 February 1996', '1995'), ('24 May 1954', '1953.'), ('18 July 2014', '2009'), ('16 January 2012', '2012'), ('5 May 1988', '1982.'), ('2 September 2015', '2015'), ('12 February 2009', '2003'), ('12 May 2008', '2008'), ('7 May 2002', '2000'), ('1 May 2017', '2017,'), ('6 August 2013', '0'), ('14 May 2007', '1948),'), ('16 September 2005', '1999.'), ('9 May 2007', '1999'), ('23 July 1998', '1987'), ('15 February 2002', '0'), ('12 August 2016', '2010'), ('25 March 1964', '1949'), ('15 October 2008', '2002'), ('16 August 1974', '1973.'), ('8 April 1991', '1990'), ('6 March 1987', '1983'), ('31 January 1968', '1967'), ('18 October 2000', '0'), ('24 February 1988', '1971'), ('11 March 2013', '(Accused'), ('27 February 1986', '1984'), ('2 July 2014', '2009'), ('4 September 2000', '1994'), ('1 August 2003', 'such'), ('11 March 1983', '1982.'), ('19 October 2006', '0'), ('26 April 1996', '1986,'), ('23 July 1993', '1992'), ('16 November 1994', '1983'), ('3 February 2001', '2001'), ('31 July 2000', '2000'), ('16 October 2015', '2008'), ('15 May 2015', '2010,'), ('3 February 2015', 'Out'), ('8 August 2002', '1995'), ('21 April 2009', '2003'), ('17 April 1990', 'v'), ('15 December 2017', '2009'), ('15 February 2008', '1993'), ('8 August 1989', '1970.'), ('10 April 1987', 'of'), ('3 September 2014', '2012'), ('23 August 1996', '1993'), ('20 July 1983', 'IIB,'), ('18 April 1969', '1967.'), ('16 November 1962', 'was'), ('10 September 2008', '2008'), ('31 January 2012', '2010)'), ('6 December 2006', 'Mali'), ('10 December 2002', '1995'), ('6 July 2009', '2007'), ('29 May 2012', '1999'), ('7 October 2003', '0'), ('23 February 1981', '1975'), ('17 December 2003', '0'), ('13 August 1984', '3129'), ('21 April 1987', '1986.'), ('2 December 2008', '2008'), ('12 April 2004', 'by'), ('27 March 2006', '2006'), ('4 September 1981', 'June'), ('21 January 1975', '1974.'), ('15 July 1999', '1999'), ('20 January 2014', '2009'), ('17 April 1980', '1970.'), ('1 October 2007', '1994.'), ('12 December 1960', '1959'), ('10 Apr

In [58]:
len(l)

2914

In [59]:
for i in range(10):
    for j in range(2):
        print(l[i][j])

26 September 1973
1973
3 September 1987
1986
11 July 2001
why
5 May 2006
2004)
3 March 2000
2000.
11 September 1962
1962
7 September 2010
2010
17 January 1968
1967.
25 November 1959
0
6 August 1982
1981

In [60]:
res = df.copy(deep=True)
print(res)

                                                   Text              Start  \
0     Masud Khan v State Of Uttar Pradesh Supreme Co...  26 September 1973
1     Prabhakaran Nair, Etc. v State Of Tamil Nadu A...   3 September 1987
2     Hiten P. Dalal v Bratindranath Banerjee Suprem...       11 July 2001
3     Ashok Kumar and Others v State of Tamil Nadu S...         5 May 2006
4     Ashok Dhingra v N.C.T. of Delhi Supreme Court ...       3 March 2000
...                                                 ...                ...
2909  Rajendra Singh v State of Uttaranchal Supreme ...      11 April 2013
2910  Food Corporation Of India & Anr v Seil Ltd. & ...    11 January 2008
2911  State of Kerala v Sasi Supreme Court of India ...    31 October 1996
2912  Columbia Sportswear Company v Director Of Inco...       30 July 2012
2913  Bharat Gurjar and others v State of Rajasthan ...       9 March 2017

        End
0      1973
1      1986
2       why
3     2004)
4     2000.
...     ...
2909   2008
2910      0
2911   1996
2912     of
2913  2016,

[2914 rows x 3 columns]

In [ ]:
#df.drop(['c', 'd'], inplace = True )

In [43]:
# v="1234567890().,/?:;{}[]"
# for i in range(100):
#     z=res.iloc[[i]]
#     print(z)
#     for j in range(len(z)):
#         if z[j] not in v:
#             new_df=new_df.drop(new_df.index[j],inplace=True)